using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Configuration;

namespace BioPM.ClassScripts
{
    public class SideBarMenu
    {
        
        public static String TopMenuElement(string username)
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("<header class='header fixed-top clearfix'>                                       ");
            sb.Append("<div class='brand'>                                                              ");
            sb.Append("<a href='PageUserPanel.aspx' class='logo'>                                       ");
            sb.Append("<p>BIO-PM</p>                                                                    ");
            sb.Append("</a>                                                                             ");
            sb.Append("<div class='sidebar-toggle-box'>                                                 ");
            sb.Append("<div class='fa fa-bars'></div>                                                   ");
            sb.Append("</div>                                                                           ");
            sb.Append("</div>                                                                           ");
            sb.Append("<div class='top-nav clearfix'>                                                   ");
            sb.Append("<!--search & user info start-->                                                  ");
            sb.Append("<ul class='nav pull-right top-menu'>                                             ");
            sb.Append("<li>                                                                             ");
            sb.Append("<input type='text' class='form-control search' placeholder=' Search'>            ");
            sb.Append("</li>                                                                            ");
            sb.Append("<!-- user login dropdown start-->                                                ");
            sb.Append("<li class='dropdown'>                                                            ");
            sb.Append("<a data-toggle='dropdown' class='dropdown-toggle' href='#'>                      ");
            sb.Append("<img alt='' src='Scripts/UserPanel/images/user.png'>                               ");
            sb.Append("<span class='username'>" + username + "</span> ");
            sb.Append("<b class='caret'></b>                                                            ");
            sb.Append("</a>                                                                             ");
            sb.Append("<ul class='dropdown-menu extended logout'>                                       ");
            if (WebConfigurationManager.AppSettings["Gateway"] == "local")
            {
	        sb.Append("<li><a href='PageUserProfile.aspx'><i class=' fa fa-suitcase'></i>Profile</a></li> ");
                sb.Append("<li><a href='PageLogin.aspx'><i class='fa fa-key'></i> Log Out</a></li>          ");
            }

            sb.Append("</ul>                                                                            ");
            sb.Append("</li>                                                                            ");
            sb.Append("<!-- user login dropdown end -->                                                 ");
            sb.Append("</ul>                                                                            ");
            sb.Append("<!--search & user info end-->                                                    ");
            sb.Append("</div>                                                                           ");
            sb.Append("</header>                                                                        ");

            return sb.ToString();
        }

        public static String LeftSidebarMenuElementAutoGenerated(string USRNM)
        {
            StringBuilder sb = new StringBuilder();
            List<object[]> menuparent = new List<object[]>();
            List<object[]> menuchild = new List<object[]>();

            if (WebConfigurationManager.AppSettings["UserMenu"].ToString() == "")
            {
                sb.Append("<aside>                                                  ");
                sb.Append("<div id='sidebar' class='nav-collapse'>                  ");
                sb.Append("<!-- sidebar menu start-->                               ");
                sb.Append("<ul class='sidebar-menu' id='nav-accordion'>             ");

                sb.Append("<li>                                                     ");
                sb.Append("<a href='PageUserPanel.aspx'>                            ");
                sb.Append("<i class='fa fa-dashboard'></i>                          ");
                sb.Append("<span>Dashboard</span>                                   ");
                sb.Append("</a>                                                     ");
                sb.Append("</li>                                                    ");

                menuparent = ClassObjects.ApplicationCatalog.GetMenuApplicationByUserID("0", USRNM);
                for (int i = 0; i < menuparent.Count; i++)
                {
                    sb.Append("<li class='sub-menu'>                                    ");
                    sb.Append("<a href='javascript:;'>                                  ");
                    sb.Append("<i class='" + (menuparent[i])[3].ToString() + "'></i>    ");
                    sb.Append("<span> " + (menuparent[i])[1].ToString() + "</span>      ");
                    sb.Append("</a>                                                     ");

                    menuchild = ClassObjects.ApplicationCatalog.GetMenuApplicationByUserID((menuparent[i])[0].ToString(), USRNM);
                    if (menuchild.Count > 0)
                    {
                        sb.Append("<ul class='sub'>");
                        for (int x = 0; x < menuchild.Count; x++)
                        {
                            sb.Append("<li><a href='" + (menuchild[x])[2].ToString() + "'> " + (menuchild[x])[1].ToString() + " </a></li>");
                        }
                        sb.Append("</ul>");
                    }
                    sb.Append("</li>                                                    ");
                }

                sb.Append("</ul>                                                    ");
                sb.Append("<!-- sidebar menu end-->                                 ");
                sb.Append("</div>                                                   ");
                sb.Append("</aside>                                                 ");

                WebConfigurationManager.AppSettings["UserMenu"] = sb.ToString();
            }
            else
            {
                sb.Append(WebConfigurationManager.AppSettings["UserMenu"].ToString());
            }
            return sb.ToString();
        }
	
	//not so important.
        public static String RightSidebarMenuElement()
        {
            StringBuilder sb = new StringBuilder();

            sb.Append("<div class='right-sidebar'>                                                                                                                                                                                      ");
            sb.Append("<div class='search-row'>                                                                                                                                                                                         ");
            sb.Append("<input type='text' placeholder='Search' class='form-control'>                                                                                                                                                    ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("<ul class='right-side-accordion'>                                                                                                                                                                                ");
            sb.Append("<li class='widget-collapsible'>                                                                                                                                                                                  ");
            sb.Append("<a href='#' class='head widget-head red-bg active clearfix'>                                                                                                                                                     ");
            sb.Append("<span class='pull-left'>work progress (5)</span>                                                                                                                                                                 ");
            sb.Append("<span class='pull-right widget-collapse'><i class='ico-minus'></i></span>                                                                                                                                        ");
            sb.Append("</a>                                                                                                                                                                                                             ");
            sb.Append("<ul class='widget-container'>                                                                                                                                                                                    ");
            sb.Append("<li>                                                                                                                                                                                                             ");
            sb.Append("<div class='prog-row side-mini-stat clearfix'>                                                                                                                                                                   ");
            sb.Append("<div class='side-graph-info'>                                                                                                                                                                                    ");
            sb.Append("<h4>Target sell</h4>                                                                                                                                                                                             ");
            sb.Append("<p>                                                                                                                                                                                                              ");
            sb.Append("25%, Deadline 12 june 13                                                                                                                                                                                         ");
            sb.Append("</p>                                                                                                                                                                                                             ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("<div class='side-mini-graph'>                                                                                                                                                                                    ");
            sb.Append("<div class='target-sell'>                                                                                                                                                                                        ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("<div class='prog-row side-mini-stat'>                                                                                                                                                                            ");
            sb.Append("<div class='side-graph-info'>                                                                                                                                                                                    ");
            sb.Append("<h4>product delivery</h4>                                                                                                                                                                                        ");
            sb.Append("<p>                                                                                                                                                                                                              ");
            sb.Append("55%, Deadline 12 june 13                                                                                                                                                                                         ");
            sb.Append("</p>                                                                                                                                                                                                             ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("<div class='side-mini-graph'>                                                                                                                                                                                    ");
            sb.Append("<div class='p-delivery'>                                                                                                                                                                                         ");
            sb.Append("<div class='sparkline' data-type='bar' data-resize='true' data-height='30' data-width='90%' data-bar-color='#39b7ab' data-bar-width='5' data-data='[200,135,667,333,526,996,564,123,890,564,455]'>               ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("<div class='prog-row side-mini-stat'>                                                                                                                                                                            ");
            sb.Append("<div class='side-graph-info payment-info'>                                                                                                                                                                       ");
            sb.Append("<h4>payment collection</h4>                                                                                                                                                                                      ");
            sb.Append("<p>                                                                                                                                                                                                              ");
            sb.Append("25%, Deadline 12 june 13                                                                                                                                                                                         ");
            sb.Append("</p>                                                                                                                                                                                                             ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("<div class='side-mini-graph'>                                                                                                                                                                                    ");
            sb.Append("<div class='p-collection'>                                                                                                                                                                                       ");
            sb.Append("<span class='pc-epie-chart' data-percent='45'>                                                                                                                                                                   ");
            sb.Append("<span class='percent'></span>                                                                                                                                                                                    ");
            sb.Append("</span>                                                                                                                                                                                                          ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("<div class='prog-row side-mini-stat'>                                                                                                                                                                            ");
            sb.Append("<div class='side-graph-info'>                                                                                                                                                                                    ");
            sb.Append("<h4>delivery pending</h4>                                                                                                                                                                                        ");
            sb.Append("<p>                                                                                                                                                                                                              ");
            sb.Append("44%, Deadline 12 june 13                                                                                                                                                                                         ");
            sb.Append("</p>                                                                                                                                                                                                             ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("<div class='side-mini-graph'>                                                                                                                                                                                    ");
            sb.Append("<div class='d-pending'>                                                                                                                                                                                          ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("<div class='prog-row side-mini-stat'>                                                                                                                                                                            ");
            sb.Append("<div class='col-md-12'>                                                                                                                                                                                          ");
            sb.Append("<h4>total progress</h4>                                                                                                                                                                                          ");
            sb.Append("<p>                                                                                                                                                                                                              ");
            sb.Append("50%, Deadline 12 june 13                                                                                                                                                                                         ");
            sb.Append("</p>                                                                                                                                                                                                             ");
            sb.Append("<div class='progress progress-xs mtop10'>                                                                                                                                                                        ");
            sb.Append("<div style='width: 50%' aria-valuemax='100' aria-valuemin='0' aria-valuenow='20' role='progressbar' class='progress-bar progress-bar-info'>                                                                      ");
            sb.Append("<span class='sr-only'>50% Complete</span>                                                                                                                                                                        ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("</li>                                                                                                                                                                                                            ");
            sb.Append("</ul>                                                                                                                                                                                                            ");
            sb.Append("</li>                                                                                                                                                                                                            ");
            sb.Append("<li class='widget-collapsible'>                                                                                                                                                                                  ");
            sb.Append("<a href='#' class='head widget-head terques-bg active clearfix'>                                                                                                                                                 ");
            sb.Append("<span class='pull-left'>contact online (5)</span>                                                                                                                                                                ");
            sb.Append("<span class='pull-right widget-collapse'><i class='ico-minus'></i></span>                                                                                                                                        ");
            sb.Append("</a>                                                                                                                                                                                                             ");
            sb.Append("<ul class='widget-container'>                                                                                                                                                                                    ");
            sb.Append("<li>                                                                                                                                                                                                             ");
            sb.Append("<div class='prog-row'>                                                                                                                                                                                           ");
            sb.Append("<div class='user-thumb'>                                                                                                                                                                                         ");
            sb.Append("<a href='#'><img src='images/avatar1_small.jpg' alt=''></a>                                                                                                                                                      ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("<div class='user-details'>                                                                                                                                                                                       ");
            sb.Append("<h4><a href='#'>Jonathan Smith</a></h4>                                                                                                                                                                          ");
            sb.Append("<p>                                                                                                                                                                                                              ");
            sb.Append("Work for fun                                                                                                                                                                                                     ");
            sb.Append("</p>                                                                                                                                                                                                             ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("<div class='user-status text-danger'>                                                                                                                                                                            ");
            sb.Append("<i class='fa fa-comments-o'></i>                                                                                                                                                                                 ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("<div class='prog-row'>                                                                                                                                                                                           ");
            sb.Append("<div class='user-thumb'>                                                                                                                                                                                         ");
            sb.Append("<a href='#'><img src='images/avatar1.jpg' alt=''></a>                                                                                                                                                            ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("<div class='user-details'>                                                                                                                                                                                       ");
            sb.Append("<h4><a href='#'>Anjelina Joe</a></h4>                                                                                                                                                                            ");
            sb.Append("<p>                                                                                                                                                                                                              ");
            sb.Append("Available                                                                                                                                                                                                        ");
            sb.Append("</p>                                                                                                                                                                                                             ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("<div class='user-status text-success'>                                                                                                                                                                           ");
            sb.Append("<i class='fa fa-comments-o'></i>                                                                                                                                                                                 ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("<div class='prog-row'>                                                                                                                                                                                           ");
            sb.Append("<div class='user-thumb'>                                                                                                                                                                                         ");
            sb.Append("<a href='#'><img src='images/chat-avatar2.jpg' alt=''></a>                                                                                                                                                       ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("<div class='user-details'>                                                                                                                                                                                       ");
            sb.Append("<h4><a href='#'>Jhone Doe</a></h4>                                                                                                                                                                               ");
            sb.Append("<p>                                                                                                                                                                                                              ");
            sb.Append("Away from Desk                                                                                                                                                                                                   ");
            sb.Append("</p>                                                                                                                                                                                                             ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("<div class='user-status text-warning'>                                                                                                                                                                           ");
            sb.Append("<i class='fa fa-comments-o'></i>                                                                                                                                                                                 ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("<div class='prog-row'>                                                                                                                                                                                           ");
            sb.Append("<div class='user-thumb'>                                                                                                                                                                                         ");
            sb.Append("<a href='#'><img src='images/avatar1_small.jpg' alt=''></a>                                                                                                                                                      ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("<div class='user-details'>                                                                                                                                                                                       ");
            sb.Append("<h4><a href='#'>Mark Henry</a></h4>                                                                                                                                                                              ");
            sb.Append("<p>                                                                                                                                                                                                              ");
            sb.Append("working                                                                                                                                                                                                          ");
            sb.Append("</p>                                                                                                                                                                                                             ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("<div class='user-status text-info'>                                                                                                                                                                              ");
            sb.Append("<i class='fa fa-comments-o'></i>                                                                                                                                                                                 ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("<div class='prog-row'>                                                                                                                                                                                           ");
            sb.Append("<div class='user-thumb'>                                                                                                                                                                                         ");
            sb.Append("<a href='#'><img src='images/avatar1.jpg' alt=''></a>                                                                                                                                                            ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("<div class='user-details'>                                                                                                                                                                                       ");
            sb.Append("<h4><a href='#'>Shila Jones</a></h4>                                                                                                                                                                             ");
            sb.Append("<p>                                                                                                                                                                                                              ");
            sb.Append("Work for fun                                                                                                                                                                                                     ");
            sb.Append("</p>                                                                                                                                                                                                             ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("<div class='user-status text-danger'>                                                                                                                                                                            ");
            sb.Append("<i class='fa fa-comments-o'></i>                                                                                                                                                                                 ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("<p class='text-center'>                                                                                                                                                                                          ");
            sb.Append("<a href='#' class='view-btn'>View all Contacts</a>                                                                                                                                                               ");
            sb.Append("</p>                                                                                                                                                                                                             ");
            sb.Append("</li>                                                                                                                                                                                                            ");
            sb.Append("</ul>                                                                                                                                                                                                            ");
            sb.Append("</li>                                                                                                                                                                                                            ");
            sb.Append("<li class='widget-collapsible'>                                                                                                                                                                                  ");
            sb.Append("<a href='#' class='head widget-head purple-bg active'>                                                                                                                                                           ");
            sb.Append("<span class='pull-left'> recent activity (3)</span>                                                                                                                                                              ");
            sb.Append("<span class='pull-right widget-collapse'><i class='ico-minus'></i></span>                                                                                                                                        ");
            sb.Append("</a>                                                                                                                                                                                                             ");
            sb.Append("<ul class='widget-container'>                                                                                                                                                                                    ");
            sb.Append("<li>                                                                                                                                                                                                             ");
            sb.Append("<div class='prog-row'>                                                                                                                                                                                           ");
            sb.Append("<div class='user-thumb rsn-activity'>                                                                                                                                                                            ");
            sb.Append("<i class='fa fa-clock-o'></i>                                                                                                                                                                                    ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("<div class='rsn-details '>                                                                                                                                                                                       ");
            sb.Append("<p class='text-muted'>                                                                                                                                                                                           ");
            sb.Append("just now                                                                                                                                                                                                         ");
            sb.Append("</p>                                                                                                                                                                                                             ");
            sb.Append("<p>                                                                                                                                                                                                              ");
            sb.Append("<a href='#'>John Sinna </a>Purchased new equipments for zonal office setup                                                                                                                                       ");
            sb.Append("</p>                                                                                                                                                                                                             ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("<div class='prog-row'>                                                                                                                                                                                           ");
            sb.Append("<div class='user-thumb rsn-activity'>                                                                                                                                                                            ");
            sb.Append("<i class='fa fa-clock-o'></i>                                                                                                                                                                                    ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("<div class='rsn-details '>                                                                                                                                                                                       ");
            sb.Append("<p class='text-muted'>                                                                                                                                                                                           ");
            sb.Append("2 min ago                                                                                                                                                                                                        ");
            sb.Append("</p>                                                                                                                                                                                                             ");
            sb.Append("<p>                                                                                                                                                                                                              ");
            sb.Append("<a href='#'>Sumon </a>Purchased new equipments for zonal office setup                                                                                                                                            ");
            sb.Append("</p>                                                                                                                                                                                                             ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("<div class='prog-row'>                                                                                                                                                                                           ");
            sb.Append("<div class='user-thumb rsn-activity'>                                                                                                                                                                            ");
            sb.Append("<i class='fa fa-clock-o'></i>                                                                                                                                                                                    ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("<div class='rsn-details '>                                                                                                                                                                                       ");
            sb.Append("<p class='text-muted'>                                                                                                                                                                                           ");
            sb.Append("1 day ago                                                                                                                                                                                                        ");
            sb.Append("</p>                                                                                                                                                                                                             ");
            sb.Append("<p>                                                                                                                                                                                                              ");
            sb.Append("<a href='#'>Mosaddek </a>Purchased new equipments for zonal office setup                                                                                                                                         ");
            sb.Append("</p>                                                                                                                                                                                                             ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("</li>                                                                                                                                                                                                            ");
            sb.Append("</ul>                                                                                                                                                                                                            ");
            sb.Append("</li>                                                                                                                                                                                                            ");
            sb.Append("<li class='widget-collapsible'>                                                                                                                                                                                  ");
            sb.Append("<a href='#' class='head widget-head yellow-bg active'>                                                                                                                                                           ");
            sb.Append("<span class='pull-left'> shipment status</span>                                                                                                                                                                  ");
            sb.Append("<span class='pull-right widget-collapse'><i class='ico-minus'></i></span>                                                                                                                                        ");
            sb.Append("</a>                                                                                                                                                                                                             ");
            sb.Append("<ul class='widget-container'>                                                                                                                                                                                    ");
            sb.Append("<li>                                                                                                                                                                                                             ");
            sb.Append("<div class='col-md-12'>                                                                                                                                                                                          ");
            sb.Append("<div class='prog-row'>                                                                                                                                                                                           ");
            sb.Append("<p>                                                                                                                                                                                                              ");
            sb.Append("Full sleeve baby wear (SL: 17665)                                                                                                                                                                                ");
            sb.Append("</p>                                                                                                                                                                                                             ");
            sb.Append("<div class='progress progress-xs mtop10'>                                                                                                                                                                        ");
            sb.Append("<div class='progress-bar progress-bar-success' role='progressbar' aria-valuenow='20' aria-valuemin='0' aria-valuemax='100' style='width: 40%'>                                                                   ");
            sb.Append("<span class='sr-only'>40% Complete</span>                                                                                                                                                                        ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("<div class='prog-row'>                                                                                                                                                                                           ");
            sb.Append("<p>                                                                                                                                                                                                              ");
            sb.Append("Full sleeve baby wear (SL: 17665)                                                                                                                                                                                ");
            sb.Append("</p>                                                                                                                                                                                                             ");
            sb.Append("<div class='progress progress-xs mtop10'>                                                                                                                                                                        ");
            sb.Append("<div class='progress-bar progress-bar-info' role='progressbar' aria-valuenow='20' aria-valuemin='0' aria-valuemax='100' style='width: 70%'>                                                                      ");
            sb.Append("<span class='sr-only'>70% Completed</span>                                                                                                                                                                       ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("</li>                                                                                                                                                                                                            ");
            sb.Append("</ul>                                                                                                                                                                                                            ");
            sb.Append("</li>                                                                                                                                                                                                            ");
            sb.Append("</ul>                                                                                                                                                                                                            ");
            sb.Append("</div>                                                                                                                                                                                                           ");
            sb.Append("<script src='Scripts/UserPanel/assets/flot-chart/jquery.flot.js'></script>");
            return sb.ToString();
        }
    }
}