<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="FormUpdateBatchTransaction.aspx.cs" Inherits="BioPM.FormUpdateBatchTransaction" %>

<!DOCTYPE html>
<script runat="server">
    protected void Page_Load(object sender, EventArgs e)
    {
        if (Session["username"] == null && Session["password"] == null) Response.Redirect("PageLogin.aspx");
        if (!IsPostBack) SetDataToForm();
    }
    protected void sessionCreator()
    {
        Session["username"] = "K495";
        Session["name"] = "ALLAN PRAKOSA";
        Session["password"] = "admin1234";
        Session["role"] = "111111";
    }

    protected void SetProduct()
    {
        ddlProductType.Items.Clear();
        foreach (object[] data in BioPM.ClassObjects.BatchCatalog.GetProduct())
        {
            ddlProductType.Items.Add(new ListItem(data[1].ToString(), data[0].ToString()));
        }
    }
    
    protected void SetDataBatch()
    {
        object[] values = BioPM.ClassObjects.BatchCatalog.GetBatchByID(Request.QueryString["key"]);
        string day = BioPM.ClassEngines.DateFormatFactory.GetDay(values[1].ToString());
        string month = BioPM.ClassEngines.DateFormatFactory.GetMonth(values[1].ToString());
        string year = BioPM.ClassEngines.DateFormatFactory.GetYear(values[1].ToString());
        txtProductionDate.Text = month+"-"+day+"-"+year;
        txtBatch.Text = values[2].ToString();
        ddlProductType.SelectedValue = values[3].ToString();
    }

    
    protected void SetDataToForm()
    {
        SetProduct();
        SetDataBatch();
    }

    protected void UpdateBatchIntoDatabasse()
    {
        BioPM.ClassObjects.BatchCatalog.UpdateBatchTransaction(Request.QueryString["key"], txtProductionDate.Text, txtBatch.Text, ddlProductType.SelectedValue, "",Session["username"].ToString());
    }

    protected void btnAdd_Click(object sender, EventArgs e)
    {
        if (IsPostBack) UpdateBatchIntoDatabasse();
        Response.Redirect("PageBatchTransaction.aspx");
    }

    protected void btnCancel_Click(object sender, EventArgs e)
    {
        Response.Redirect("PageUserPanel.aspx");
    }
</script>

<html lang="en">
<head>
   <% Response.Write(BioPM.ClassScripts.BasicScripts.GetMetaScript()); %>

    <title>BATCH UPDATE</title>

<% Response.Write(BioPM.ClassScripts.StyleScripts.GetCoreStyle()); %>
<% Response.Write(BioPM.ClassScripts.StyleScripts.GetFormStyle()); %>
<% Response.Write(BioPM.ClassScripts.StyleScripts.GetCustomStyle()); %>
</head>

<body>

<section id="container" >
 
<!--header start--> 
 <%Response.Write( BioPM.ClassScripts.SideBarMenu.TopMenuElement(Session["name"].ToString()) ); %> 
<!--header end-->
   
<!--left side bar start-->
 <%Response.Write(BioPM.ClassScripts.SideBarMenu.LeftSidebarMenuElementAutoGenerated(Session["username"].ToString())); %> 
<!--left side bar end-->

    <!--main content start-->
    <section id="main-content">
        <section class="wrapper">
        <!-- page start-->

        <div class="row">
            <div class="col-sm-12">
                <section class="panel">
                    <header class="panel-heading">
                        BATCH UPDATE FORM
                          <span class="tools pull-right">
                            <a class="fa fa-chevron-down" href="javascript:;"></a>
                            <a class="fa fa-times" href="javascript:;"></a>
                         </span>
                    </header>
                    <div class="panel-body">
                        <form class="form-horizontal " runat="server" >
                         
                        <div class="form-group">
                            <label class="col-sm-3 control-label"> BATCH </label>
                            <div class="col-lg-3 col-md-4">
                                <asp:TextBox ID="txtBatch" runat="server" class="form-control m-bot15" placeholder="BATCH NUMBER" ></asp:TextBox>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> PRODUCT NAME </label>
                            <div class="col-lg-3 col-md-4">
                            <asp:DropDownList ID="ddlProductType" runat="server" class="form-control m-bot15">   
                                
                                </asp:DropDownList> 
                            </div>
                        </div>
                            
                        <div class="form-group">
                            <label class="col-sm-3 control-label"> PRODUCTION DATE </label>
                            <div class="col-md-4 col-lg-3">
                                <asp:TextBox ID="txtProductionDate" value="" size="16" class="form-control form-control-inline input-medium default-date-picker" runat="server"></asp:TextBox>
                                <span class="help-block">Production Date Format : month-day-year e.g. 01-31-2014</span>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> </label>
                            <div class="col-lg-3 col-md-3">
                                <asp:Button class="btn btn-round btn-primary" ID="btnAdd" runat="server" Text="Update" OnClick="btnAdd_Click"/>
                                <asp:Button class="btn btn-round btn-primary" ID="btnCancel" runat="server" Text="Cancel" OnClick="btnCancel_Click"/>
                            </div>
                        </div>
                            
                        </form>
                    </div>
                    
                </section>
            </div>
        </div>
        <!-- page end-->
        </section>
    </section>
    <!--main content end-->
<!--right sidebar start-->
    <%Response.Write(BioPM.ClassScripts.SideBarMenu.RightSidebarMenuElement()); %> 
<!--right sidebar end-->
</section>

<!-- Placed js at the end of the document so the pages load faster -->
<% Response.Write(BioPM.ClassScripts.JS.GetCoreScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetCustomFormScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetInitialisationScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetPieChartScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetSparklineChartScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetFlotChartScript()); %>
</body>
</html>
