<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="FormInputLabelBatch.aspx.cs" Inherits="BioPM.FormInputLabelBatch" %>

<!DOCTYPE html>
<script runat="server">
    protected void Page_Load(object sender, EventArgs e)
    {
        if (Session["username"] == null && Session["password"] == null) Response.Redirect("PageLogin.aspx");
        if (!IsPostBack)
        {
            GetDataCostCenter();
            GetDataLabel();
            SetDataToForm(Request.QueryString["key"]);
        }
    }
    protected void sessionCreator()
    {
        Session["username"] = "K495";
        Session["name"] = "ALLAN PRAKOSA";
        Session["password"] = "admin1234";
        Session["role"] = "111111";
    }

    protected void SetDataToForm(string ID)
    {
        object[] values = BioPM.ClassObjects.LabelCatalog.GetLabelBatchByID(ID);
        txtBatch.Text = values[0].ToString();
        txtGin.Text = values[1].ToString();
        txtProductName.Text = values[3].ToString();
        ddlLabel.SelectedValue = values[5].ToString();
        Session["PRDID"] = values[6].ToString();
        ddlCostCenter.SelectedValue = values[7].ToString();
    }
    
    protected void GetDataCostCenter()
    {
        ddlCostCenter.Items.Clear();
        foreach (object[] data in BioPM.ClassObjects.CostCenterCatalog.GetAllCostCenter())
        {
            ddlCostCenter.Items.Add(new ListItem(data[1].ToString(), data[0].ToString()));
        }
    }
    
    protected void GetDataLabel()
    {
        ddlLabel.Items.Clear();
        foreach(object[] data in BioPM.ClassObjects.LabelCatalog.GetLabels())
        {
            ddlLabel.Items.Add(new ListItem(data[1].ToString(), data[0].ToString()));
        }
    }
    
    protected void InsertDataIntoDatabase()
    {
        BioPM.ClassObjects.LabelCatalog.UpdateLabelBatch(txtBatch.Text, txtGin.Text, ddlLabel.SelectedValue, Session["PRDID"].ToString(), ddlCostCenter.SelectedValue, Session["username"].ToString());
    }

    protected void txtBatch_TextChanged(object sender, EventArgs e)
    {
        if (BioPM.ClassObjects.ProductionCatalog.ValidateProductBatch(txtBatch.Text) >= 1)
        {
            object[] values = BioPM.ClassObjects.ProductionCatalog.GetProductBatchByBatch(txtBatch.Text);
            Session["PRDID"] = values[2].ToString();
            txtProductName.Text = values[3].ToString();
        }
        else
        {
            ClientScript.RegisterStartupScript(this.GetType(), "myalert", "alert('" + BioPM.ClassEngines.ValidationFactory.GetErrorMessage(10, "BATCH", "") + "');", true);
            txtBatch.Text = "";
        }
    }

    protected void btnAdd_Click(object sender, EventArgs e)
    {
        InsertDataIntoDatabase();
        Response.Redirect("PageLabel.aspx");
    }

    protected void btnCancel_Click(object sender, EventArgs e)
    {
        Response.Redirect("PageUserPanel.aspx");
    }
</script>

<html lang="en">
<head>
    <% Response.Write(BioPM.ClassScripts.BasicScripts.GetMetaScript()); %>

    <title>LABEL UPDATE</title>

    <% Response.Write(BioPM.ClassScripts.StyleScripts.GetCoreStyle()); %>
<% Response.Write(BioPM.ClassScripts.StyleScripts.GetFormStyle()); %>
<% Response.Write(BioPM.ClassScripts.StyleScripts.GetCustomStyle()); %>
</head>

<body>

<section id="container" >
 
<!--header start--> 
 <%Response.Write( BioPM.ClassScripts.SideBarMenu.TopMenuElement(Session["name"].ToString()) ); %> 
<!--header end-->
   
<!--left side bar start-->
 <%Response.Write(BioPM.ClassScripts.SideBarMenu.LeftSidebarMenuElementAutoGenerated(Session["username"].ToString())); %> 
<!--left side bar end-->

    <!--main content start-->
    <section id="main-content">
        <section class="wrapper">
        <!-- page start-->

        <div class="row">
            <div class="col-sm-12">
                <section class="panel">
                    <header class="panel-heading">
                        LABEL UPDATE FORM
                          <span class="tools pull-right">
                            <a class="fa fa-chevron-down" href="javascript:;"></a>
                            <a class="fa fa-times" href="javascript:;"></a>
                         </span>
                    </header>
                    <div class="panel-body">
                        <form class="form-horizontal " runat="server" >
                         
                        <div class="form-group">
                            <label class="col-sm-3 control-label"> BATCH </label>
                            <div class="col-lg-3 col-md-4">
                                <asp:TextBox ID="txtBatch" runat="server"  OnTextChanged="txtBatch_TextChanged" class="form-control m-bot15" placeholder="BATCH" ></asp:TextBox>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> GIN </label>
                            <div class="col-lg-3 col-md-4">
                                <asp:TextBox ID="txtGin" runat="server" class="form-control m-bot15" placeholder="GIN" ></asp:TextBox>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label class="col-sm-3 control-label"> PRODUCT NAME </label>
                            <div class="col-lg-3 col-md-4">
                                <asp:Label ID="txtProductName" runat="server" class="form-control m-bot15"></asp:Label>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> LABEL </label>
                            <div class="col-lg-3 col-md-4">
                                <asp:DropDownList ID="ddlLabel" runat="server" class="form-control m-bot15">   
                                </asp:DropDownList> 
                            </div>
                        </div>
                                
                        <div class="form-group">
                            <label class="col-sm-3 control-label"> COST CENTER </label>
                            <div class="col-lg-3 col-md-4">
                                <asp:DropDownList ID="ddlCostCenter" runat="server" class="form-control m-bot15">   
                                </asp:DropDownList> 
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> </label>
                            <div class="col-lg-3 col-md-3">
                                <asp:Button class="btn btn-round btn-primary" ID="btnAdd" runat="server" Text="Update" OnClick="btnAdd_Click"/>
                                <asp:Button class="btn btn-round btn-primary" ID="btnCancel" runat="server" Text="Cancel" OnClick="btnCancel_Click"/>
                            </div>
                        </div>
                            
                        </form>
                    </div>
                    
                </section>
            </div>
        </div>
        <!-- page end-->
        </section>
    </section>
    <!--main content end-->
<!--right sidebar start-->
    <%Response.Write(BioPM.ClassScripts.SideBarMenu.RightSidebarMenuElement()); %> 
<!--right sidebar end-->
</section>

<!-- Placed js at the end of the document so the pages load faster -->
    <% Response.Write(BioPM.ClassScripts.JS.GetCoreScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetCustomFormScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetInitialisationScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetPieChartScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetSparklineChartScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetFlotChartScript()); %>
</body>
</html>
