<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="FormReportQCTest.aspx.cs" Inherits="BioPM.FormReportQCTest" %>

<!DOCTYPE html>
<script runat="server">
    Random rand = new Random();
    protected void Page_Load(object sender, EventArgs e)
    {
        if (Session["username"] == null && Session["password"] == null) Response.Redirect("PageLogin.aspx");
        if (!IsPostBack) GetQCTestType();
    }
    protected void sessionCreator()
    {
        Session["username"] = "K495";
        Session["name"] = "ALLAN PRAKOSA";
        Session["password"] = "admin1234";
        Session["role"] = "111111";
    }
    
    protected void GetQCTestType()
    {
        //ddlQCType.Items.Clear();
        //foreach (object[] data in BioPM.ClassObjects.QualityControlCatalog.GetAnimalMouseType())
        //{
        //    ddlQCType.Items.Add(new ListItem(data[1].ToString(), data[0].ToString()));
        //}
    }

    protected void ddlQCType_SelectedIndexChanged(object sender, EventArgs e)
    {
        if (IsPostBack)
        {
            if (ddlQCType.SelectedValue == "1") GetRandomAnimalDate();
            else GetQCRandomDateTest();
        }
    }

    protected void GetRandomAnimalDate()
    {
        ddlRandomDate.Items.Clear();
        foreach (object[] data in BioPM.ClassObjects.QualityControlCatalog.GetAnimalTestRandomDate())
        {
            if (BioPM.ClassObjects.QualityControlCatalog.GetCageAndAnimalNumberByID(data[0].ToString())[0].ToString() != "0")
                ddlRandomDate.Items.Add(new ListItem(BioPM.ClassEngines.DateFormatFactory.GetDateFormat(data[1].ToString()) + " - " + data[2].ToString(), data[0].ToString()));
        }
    }
    
    protected void GetQCRandomDateTest()
    {
        ddlRandomDate.Items.Clear();
        foreach (object[] data in BioPM.ClassObjects.QualityControlCatalog.GetQCTestRandomDate(ddlQCType.SelectedValue))
        {
            if (BioPM.ClassObjects.QualityControlCatalog.GetCageAndAnimalNumberByID(data[0].ToString())[0].ToString() != "0")
                ddlRandomDate.Items.Add(new ListItem(BioPM.ClassEngines.DateFormatFactory.GetDateFormat(data[1].ToString()) + " - " + data[2].ToString(), data[0].ToString()));
        }
    }

    protected void btnAdd_Click(object sender, EventArgs e)
    {
        Session["id"] = ddlRandomDate.SelectedValue;
        
        //Response.Redirect("PageReportAnimalTest.aspx");
        Response.Redirect("PageReportSampleRandom.aspx");
    }

    protected void btnCancel_Click(object sender, EventArgs e)
    {
        Response.Redirect("PageUserPanel.aspx");
    }
</script>

<html lang="en">
<head>
    <% Response.Write(BioPM.ClassScripts.BasicScripts.GetMetaScript()); %>

    <title>QC TEST REPORT</title>

<% Response.Write(BioPM.ClassScripts.StyleScripts.GetCoreStyle()); %>
<% Response.Write(BioPM.ClassScripts.StyleScripts.GetFormStyle()); %>
<% Response.Write(BioPM.ClassScripts.StyleScripts.GetCustomStyle()); %>
</head>

<body>

<section id="container" >
 
<!--header start--> 
 <%Response.Write( BioPM.ClassScripts.SideBarMenu.TopMenuElement(Session["name"].ToString()) ); %> 
<!--header end-->
   
<!--left side bar start-->
 <%Response.Write(BioPM.ClassScripts.SideBarMenu.LeftSidebarMenuElementAutoGenerated(Session["username"].ToString())); %> 
<!--left side bar end-->

    <!--main content start-->
    <section id="main-content">
        <section class="wrapper">
        <!-- page start-->

        <div class="row">
            <div class="col-sm-12">
                <section class="panel">
                    <header class="panel-heading">
                        QC TEST REPORT ENTRY FORM
                          <span class="tools pull-right">
                            <a class="fa fa-chevron-down" href="javascript:;"></a>
                            <a class="fa fa-times" href="javascript:;"></a>
                         </span>
                    </header>
                    <div class="panel-body">
                        <form class="form-horizontal " runat="server" >
                        
                        <div class="form-group">
                            <label class="col-sm-3 control-label"> QC TEST TYPE </label>
                            <div class="col-lg-3 col-md-4">
                            <asp:DropDownList ID="ddlQCType" AutoPostBack="true" runat="server" class="form-control m-bot15" OnSelectedIndexChanged="ddlQCType_SelectedIndexChanged">   
                                <asp:ListItem Value="1"> QC Animal Random </asp:ListItem>
                                <asp:ListItem Value="6"> QC MWGT </asp:ListItem>
                                <asp:ListItem Value="13"> QC Diphtheria </asp:ListItem>
                                <asp:ListItem Value="14"> QC Tetanus Potency </asp:ListItem>
                                <asp:ListItem Value="15"> QC Pertussis Potency </asp:ListItem>
                                </asp:DropDownList> 
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> RANDOM DATE </label>
                            <div class="col-lg-3 col-md-4">
                            <asp:DropDownList ID="ddlRandomDate" AutoPostBack="true" runat="server" class="form-control m-bot15"> 
                                </asp:DropDownList> 
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> </label>
                            <div class="col-lg-3 col-md-3">
                                <asp:Button class="btn btn-round btn-primary" ID="btnAdd" runat="server" Text="View" OnClick="btnAdd_Click"/>
                                <asp:Button class="btn btn-round btn-primary" ID="btnCancel" runat="server" Text="Cancel" OnClick="btnCancel_Click"/>
                            </div>
                        </div>
                            
                        </form>
                    </div>
                    
                </section>
            </div>
        </div>
        <!-- page end-->
        </section>
    </section>
    <!--main content end-->
<!--right sidebar start-->
    <%Response.Write(BioPM.ClassScripts.SideBarMenu.RightSidebarMenuElement()); %> 
<!--right sidebar end-->
</section>

<!-- Placed js at the end of the document so the pages load faster -->
    
<% Response.Write(BioPM.ClassScripts.JS.GetCoreScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetCustomFormScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetInitialisationScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetPieChartScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetSparklineChartScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetFlotChartScript()); %>
</body>
</html>
