<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="FormEvaluasiImplementasi.aspx.cs" Inherits="BioPM.FormEvaluasiImplementasi" %>

<!DOCTYPE html>
<script runat="server">
    protected void Page_Load(object sender, EventArgs e)
    {
        if (Session["username"] == null && Session["password"] == null) Response.Redirect("PageLogin.aspx");
    }

    protected void InsertAnswersIntoDatabase()
    {
        int ANSID;
        ANSID = BioPM.ClassObjects.Survey.GetAnswersMaxID() + 1;
        BioPM.ClassObjects.Survey.SubmitAnswers(ANSID.ToString(), Request.QueryString["key"].ToString(), "8", rbSoal1.SelectedValue, Session["username"].ToString());
        ANSID = BioPM.ClassObjects.Survey.GetAnswersMaxID() + 1;
        BioPM.ClassObjects.Survey.SubmitAnswers(ANSID.ToString(), Request.QueryString["key"].ToString(), "9", rbSoal2.SelectedValue, Session["username"].ToString());
        ANSID = BioPM.ClassObjects.Survey.GetAnswersMaxID() + 1;
        BioPM.ClassObjects.Survey.SubmitAnswers(ANSID.ToString(), Request.QueryString["key"].ToString(), "10", rbSoal3.SelectedValue, Session["username"].ToString());
        ANSID = BioPM.ClassObjects.Survey.GetAnswersMaxID() + 1;
        BioPM.ClassObjects.Survey.SubmitAnswers(ANSID.ToString(), Request.QueryString["key"].ToString(), "11", rbSoal4.SelectedValue, Session["username"].ToString());
        ANSID = BioPM.ClassObjects.Survey.GetAnswersMaxID() + 1;
        BioPM.ClassObjects.Survey.SubmitAnswers(ANSID.ToString(), Request.QueryString["key"].ToString(), "12", TextArea1.Text, Session["username"].ToString());

    }

    protected void btnAdd_Click(object sender, EventArgs e)
    {
        if (IsPostBack) InsertAnswersIntoDatabase();
        Response.Redirect("PageTrainingSurvey.aspx");
    }

    protected void btnCancel_Click(object sender, EventArgs e)
    {
        Response.Redirect("PageUserPanel.aspx");
    }

    protected void btnSave_Click(object sender, EventArgs e)
    {
        //if (Session["password"].ToString() == BioPM.ClassEngines.CryptographFactory.Encrypt(txtConfirmation.Text, true))
        //{
        //    InsertCompetencyIntoDatabase();
        //    Response.Redirect("PageCompetencyParameter.aspx");
        //}
        //else
        //{
        //    ClientScript.RegisterStartupScript(this.GetType(), "myalert", "alert('" + "YOUR PASSWORD IS INCORRECT" + "');", true);
        //}
    }
</script>

<html lang="en">
<head>
    <% Response.Write(BioPM.ClassScripts.BasicScripts.GetMetaScript()); %>

    <title>Evaluasi III (Implementasi)</title>

    <% Response.Write(BioPM.ClassScripts.StyleScripts.GetCoreStyle()); %>
    <% Response.Write(BioPM.ClassScripts.StyleScripts.GetFormStyle()); %>
    <% Response.Write(BioPM.ClassScripts.StyleScripts.GetCustomStyle()); %>
</head>

<body>

<section id="container" >
 
<!--header start--> 
 <%Response.Write( BioPM.ClassScripts.SideBarMenu.TopMenuElement(Session["name"].ToString()) ); %> 
<!--header end-->
   
<!--left side bar start-->
 <%Response.Write(BioPM.ClassScripts.SideBarMenu.LeftSidebarMenuElementAutoGenerated(Session["username"].ToString())); %> 
<!--left side bar end-->

    <!--main content start-->
    <section id="main-content">
        <section class="wrapper">
        <!-- page start-->

        <div class="row">
            <div class="col-sm-12">
                <section class="panel">
                    <header class="panel-heading">
                        Evaluasi III (EVALUASI IMPLEMENTASI PELATIHAN)
                          <span class="tools pull-right">
                            <a class="fa fa-chevron-down" href="javascript:;"></a>
                            <a class="fa fa-times" href="javascript:;"></a>
                         </span>
                    </header>
                    
                    <div class="panel-body">
                        <form id="Form1" class="form-horizontal " runat="server" >
                        
                        <div class="form-group">
                            <label class="col-sm-3 control-label"> Topik Pelatihan </label>
                            <div class="col-lg-3 col-md-4">
                                <asp:TextBox ID="txtTopik" runat="server" class="form-control m-bot15" placeholder="Topik Pelatihan"></asp:TextBox>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> Nama Peserta Pelatihan </label>
                            <div class="col-lg-3 col-md-4">
                                <asp:TextBox ID="txtNama" runat="server" class="form-control m-bot15" placeholder="Nama Peserta Pelatihan" ></asp:TextBox>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> Nama & Jabatan Pengevaluasi Pelatihan </label>
                            <div class="col-lg-3 col-md-4">
                                <asp:TextBox ID="txtNamaJabatan" runat="server" class="form-control m-bot15" placeholder="Nama & Jabatan Pengevaluasi Pelatihan" ></asp:TextBox>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> Tanggal </label>
                            <div class="col-lg-3 col-md-4">
                                <asp:TextBox ID="txtTanggal" runat="server" class="form-control m-bot15" placeholder="Tanggal pelaksanaan" ></asp:TextBox>
                            </div>
                        </div>

                        <hr />

                        <label>SKALA NILAI</label>
                        <table class="table table-striped table-hover table-bordered" id="Table1" >
                            <tr>
                                <th>1</th>
                                <th>2</th>
                                <th>3</th>
                                <th>4</th>
                                <th>5</th>
                            </tr>
                            <tr>
                                <td>Kurang</td>
                                <td>Sedikit</td>
                                <td>Cukup</td>
                                <td>Banyak</td>
                                <td>Sangat Banyak</td>
                            </tr>
                        </table>

                        <table class="table table-striped table-hover table-bordered" id="survey" >
                            <tr>
                                <th>No</th>
                                <th>ASPEK</th>
                                <th colspan="5">EVALUASI</th>
                            </tr>
                            <tr>
                                <td>1</td>
                                <td>Dalam melaksanakan tugasnya apakah hasil pelatihan sudah diaplikasikan dalam pekerjaannya?</td>
                                <td>
                                    <div class="radio disable">
                                        <asp:RadioButtonList ID="rbSoal1" runat="server" RepeatDirection="Horizontal">
                                            <asp:ListItem Text ="1" Value="1" />
                                            <asp:ListItem Text ="2" Value="2" />
                                            <asp:ListItem Text ="3" Value="3" />
                                            <asp:ListItem Text ="4" Value="4" />
                                            <asp:ListItem Text ="5" Value="5" />
                                        </asp:RadioButtonList>
                                    </div></td>
                            </tr>
                            <tr>
                                <td>2</td>
                                <td>Dalam melaksanakan tugasnya apakah sudah ada perbaikan dalam pekerjaannya?</td>
                                <td>
                                    <div class="radio disable">
	                                    <asp:RadioButtonList ID="rbSoal2" runat="server" RepeatDirection="Horizontal">
                                            <asp:ListItem Text ="1" Value="1" />
                                            <asp:ListItem Text ="2" Value="2" />
                                            <asp:ListItem Text ="3" Value="3" />
                                            <asp:ListItem Text ="4" Value="4" />
                                            <asp:ListItem Text ="5" Value="5" />
                                        </asp:RadioButtonList>
                                    </div></td>                                
                            </tr>
                            <tr>
                                <td>3</td>
                                <td>Dalam melaksanakan tugasnya apakah ada peningkatan kualitas dalam bekerja?</td>
                                <td>
                                    <div class="radio disable">
	                                    <asp:RadioButtonList ID="rbSoal3" runat="server" RepeatDirection="Horizontal">
                                            <asp:ListItem Text ="1" Value="1" />
                                            <asp:ListItem Text ="2" Value="2" />
                                            <asp:ListItem Text ="3" Value="3" />
                                            <asp:ListItem Text ="4" Value="4" />
                                            <asp:ListItem Text ="5" Value="5" />
                                        </asp:RadioButtonList>
                                    </div></td>                                
                            </tr>
                            <tr>
                                <td>4</td>
                                <td>Setelah mengikuti pelatihan, apakah ada perubahan sikap dan perilaku kerja dalam
                                    menjalankan perannya sebagai karyawan secara keseluruhan?
                                </td>
                                <td>
                                    <div class="radio disable">
	                                    <asp:RadioButtonList ID="rbSoal4" runat="server" RepeatDirection="Horizontal">
                                            <asp:ListItem Text ="1" Value="1" />
                                            <asp:ListItem Text ="2" Value="2" />
                                            <asp:ListItem Text ="3" Value="3" />
                                            <asp:ListItem Text ="4" Value="4" />
                                            <asp:ListItem Text ="5" Value="5" />
                                        </asp:RadioButtonList>
                                    </div></td>                                
                            </tr>
                        </table>

                        <hr />

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> Saran: </label>
                            <div class="col-lg-3 col-md-4">
                                <asp:TextBox id="TextArea1" TextMode="multiline" Columns="60" Rows="3" runat="server" />
                                </div>
                        </div>

                        <!-- Modal -->
                        <div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="myModal" class="modal fade">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                        <h4 class="modal-title">Approver Confirmation</h4>
                                    </div>
                                    <div class="modal-body">
                                        <p>You Are Logged In As <% Response.Write(Session["name"].ToString()); %></p><br />
                                        <p>Are you sure to insert into database?</p>
                                        <asp:TextBox ID="txtConfirmation" runat="server" TextMode="Password" placeholder="Confirmation Password" class="form-control placeholder-no-fix"></asp:TextBox>

                                    </div>
                                    <div class="modal-footer">
                                        <asp:Button ID="btnClose" runat="server" data-dismiss="modal" class="btn btn-default" Text="Cancel"></asp:Button>
                                        <asp:Button ID="btnSubmit" runat="server" class="btn btn-success" Text="Confirm" OnClick="btnSave_Click"></asp:Button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- modal -->

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> </label>
                            <div class="col-lg-3 col-md-3">
                                <asp:Button class="btn btn-round btn-primary" ID="btnAdd" runat="server" Text="Add" OnClick="btnAdd_Click"/>
                                <asp:Button class="btn btn-round btn-primary" ID="btnCancel" runat="server" Text="Cancel" OnClick="btnCancel_Click"/>
                            </div>
                        </div>
                            
                        </form>
                    </div>
                    
                </section>
            </div>
        </div>
        <!-- page end-->
        </section>
    </section>
    <!--main content end-->
<!--right sidebar start-->
    <%Response.Write(BioPM.ClassScripts.SideBarMenu.RightSidebarMenuElement()); %> 
<!--right sidebar end-->
</section>

<!-- Placed js at the end of the document so the pages load faster -->
   
<% Response.Write(BioPM.ClassScripts.JS.GetCoreScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetCustomFormScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetInitialisationScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetPieChartScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetSparklineChartScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetFlotChartScript()); %>
</body>
</html>
