<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="FormInputTargetTraining.aspx.cs" Inherits="BioPM.FormInputTargetTraining" %>

<!DOCTYPE html>
<script runat="server">
    protected void Page_Load(object sender, EventArgs e)
    {
        if (Session["username"] == null && Session["password"] == null) Response.Redirect("PageLogin.aspx");
        if (!IsPostBack) SetCompetencyAndEventList();
    }

    protected void SetCompetencyAndEventList()
    {
        ddlCompetency.Items.Clear();
        foreach (object[] data in BioPM.ClassObjects.CompetencyCatalog.GetAllCompetency())
        {
            ddlCompetency.Items.Add(new ListItem(data[1].ToString(), data[0].ToString()));
        }

        ddlEvtName.Items.Clear();
        foreach (object[] data in BioPM.ClassObjects.ComDevEvent.GetAllComdevEvent())
        {
            ddlEvtName.Items.Add(new ListItem(data[1].ToString(), data[0].ToString()));
        }
    }

    protected void InsertTargetIntoDatabase()
    {
        string TRGID = (BioPM.ClassObjects.ComDevEvent.GetComDevEventTargetMaxID() + 1).ToString();
        BioPM.ClassObjects.ComDevEvent.InsertComDevEventTarget(TRGID, ddlEvtName.SelectedValue, ddlCompetency.SelectedValue, txtLevelTarget.Text, Session["username"].ToString());
    }

    protected void btnAdd_Click(object sender, EventArgs e)
    {
        Response.Redirect("PageCompetencyDevelopmentEvent.aspx");
    }

    protected void btnAddComp_Click(object sender, EventArgs e)
    {
        if (IsPostBack) InsertTargetIntoDatabase();
        Response.Redirect("FormInputTargetTraining.aspx?key=" + ddlEvtName.SelectedValue + "");
    }

    protected void btnCancel_Click(object sender, EventArgs e)
    {
        Response.Redirect("PageUserPanel.aspx");
    }

    protected String GenerateDataKompetensi()
    {
        string htmlelement = "";

        foreach (object[] data in BioPM.ClassObjects.ComDevEvent.GetComdevEventTargetByEvent(Request.QueryString["key"].ToString()))
        {
            htmlelement += "<tr class=''><td>" + data[3].ToString() + "</td><td>" + data[4].ToString() + "</td><td><a class='edit' href='FormUpdateEventMethod.aspx?key=" + data[0].ToString() + "'>Edit</a></td><td><a class='delete' href='PageInformation.aspx?key=" + data[0].ToString() + "&type=23'>Delete</a></td></tr>";
        }

        return htmlelement;
    }
</script>

<html lang="en">
<head>
    <% Response.Write(BioPM.ClassScripts.BasicScripts.GetMetaScript()); %>

    <title>Event Target Entry Form</title>

    <% Response.Write(BioPM.ClassScripts.StyleScripts.GetCoreStyle()); %>
    <% Response.Write(BioPM.ClassScripts.StyleScripts.GetFormStyle()); %>
    <% Response.Write(BioPM.ClassScripts.StyleScripts.GetCustomStyle()); %>
</head>

<body>

<section id="container" >
 
<!--header start--> 
 <%Response.Write( BioPM.ClassScripts.SideBarMenu.TopMenuElement(Session["name"].ToString()) ); %> 
<!--header end-->
   
<!--left side bar start-->
 <%Response.Write(BioPM.ClassScripts.SideBarMenu.LeftSidebarMenuElementAutoGenerated(Session["username"].ToString())); %> 
<!--left side bar end-->

    <!--main content start-->
    <section id="main-content">
        <section class="wrapper">
        <!-- page start-->

        <div class="row">
            <div class="col-sm-12">
                <section class="panel">
                    <header class="panel-heading">
                        Event Target Entry Form
                          <span class="tools pull-right">
                            <a class="fa fa-chevron-down" href="javascript:;"></a>
                            <a class="fa fa-times" href="javascript:;"></a>
                         </span>
                    </header>
                    <div class="panel-body">
                        <form id="Form1" class="form-horizontal " runat="server" >

                        COMPETENCY TO DEVELOP

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> EVENT NAME </label>
                            <div class="col-lg-3 col-md-4">
                                <asp:DropDownList ID="ddlEvtName" runat="server" class="form-control m-bot15">   
                                </asp:DropDownList> 
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> COMPETENCY NAME </label>
                            <div class="col-lg-3 col-md-4">
                                <asp:DropDownList ID="ddlCompetency" runat="server" class="form-control m-bot15">   
                                </asp:DropDownList> 
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> PROFICIENCY LEVEL TARGET </label>
                            <div class="col-lg-3 col-md-4">
                                <asp:TextBox ID="txtLevelTarget" runat="server" class="form-control m-bot15" placeholder="PROFICIENCY LEVEL TARGET" ></asp:TextBox>
                            </div>
                        </div>

                        <asp:Button class="btn btn-round btn-primary" ID="addComp" runat="server" Text="Add Competency" OnClick="btnAddComp_Click"/>

                        <table class="table table-striped table-hover table-bordered" id="dynamic-table" >
                                <thead>
                                <tr>
                                    <th>Competency Name</th>
                                    <th>Proficiency Level Target</th>
                                    <th>Delete</th>
                                </tr>
                                </thead>
                                <tbody>
                                <% Response.Write(GenerateDataKompetensi()); %>
                                </tbody>
                        </table>

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> </label>
                            <div class="col-lg-3 col-md-3">
                                <asp:Button class="btn btn-round btn-primary" ID="btnAdd" runat="server" Text="Finish" OnClick="btnAdd_Click"/>
                                <asp:Button class="btn btn-round btn-primary" ID="btnCancel" runat="server" Text="Cancel" OnClick="btnCancel_Click"/>
                            </div>
                        </div>
                            
                        </form>
                    </div>
                    
                </section>
            </div>
        </div>
        <!-- page end-->
        </section>
    </section>
    <!--main content end-->
<!--right sidebar start-->
    <%Response.Write(BioPM.ClassScripts.SideBarMenu.RightSidebarMenuElement()); %> 
<!--right sidebar end-->
</section>

<!-- Placed js at the end of the document so the pages load faster -->
   
<% Response.Write(BioPM.ClassScripts.JS.GetCoreScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetCustomFormScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetInitialisationScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetPieChartScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetSparklineChartScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetFlotChartScript()); %>
</body>
</html>
