<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="FormSuggestTraining.aspx.cs" Inherits="BioPM.FormSuggestTraining" %>

<!DOCTYPE html>
<script runat="server">
    protected void Page_Load(object sender, EventArgs e)
    {
        if (Session["username"] == null && Session["password"] == null) Response.Redirect("PageLogin.aspx");
        if (!IsPostBack)
        {
            GetDataEvent();
            GetDataEmployee();
        }
    }
    
    protected void GetDataEvent()
    {
        ddlEventName.Items.Clear();
        foreach (object[] data in BioPM.ClassObjects.ComDevEvent.GetAllComdevEvent())
        {
            ddlEventName.Items.Add(new ListItem(data[1].ToString(), data[0].ToString()));
        }
    }

    protected void GetDataEmployee()
    {
        ddlEmployeeName.Items.Clear();
        foreach (object[] data in BioPM.ClassObjects.EmployeeCatalog.GetEmployeeByPosition(Session["username"].ToString()))
        {
            ddlEmployeeName.Items.Add(new ListItem(data[1].ToString(), data[0].ToString()));
        }
    }

    protected void InsertReasonIntoDatabase()
    {
        BioPM.ClassObjects.Reason.InsertReason(txtReason.Text, "Suggest Training", Session["username"].ToString());
    }
    
    protected void InsertDataIntoDatabase()
    {
        string RECID = (BioPM.ClassObjects.ComDevPlan.GetComDevPlanMaxID() + 1).ToString();
        string m = txtMonth.Text.Substring(0, 2);
        string year = txtMonth.Text.Substring(6, 4);
        string month = BioPM.ClassEngines.DateFormatFactory.enumToString(m)+" "+year;
        BioPM.ClassObjects.ComDevPlan.InsertComDevPlan(RECID, ddlEmployeeName.SelectedValue, ddlEventName.SelectedValue, month, txtCost.Text, txtDuration.Text, Session["username"].ToString());
        BioPM.ClassObjects.ComDevPlan.InsertComDevPlanStatus(RECID, "Suggested", " ", Session["username"].ToString());
    }

    protected void btnAdd_Click(object sender, EventArgs e)
    {
        InsertDataIntoDatabase();
        Response.Redirect("PageSuggestTraining.aspx");
    }

    protected void btnAddComp_Click(object sender, EventArgs e)
    {
        InsertDataIntoDatabase();
        Response.Redirect("PageLabel.aspx");
    }

    protected void btnCancel_Click(object sender, EventArgs e)
    {
        Response.Redirect("PageUserPanel.aspx");
    }

    protected String GenerateDataKompetensi()
    {
        string htmlelement = " ";
        
        return htmlelement;
    }

    protected void btnSave_Click(object sender, EventArgs e)
    {
        if (Session["password"].ToString() == BioPM.ClassEngines.CryptographFactory.Encrypt(txtConfirmation.Text, true))
        {
            InsertDataIntoDatabase();
            InsertReasonIntoDatabase();
            Response.Redirect("PageSuggestTraining.aspx");
        }
        else
        {
            ClientScript.RegisterStartupScript(this.GetType(), "myalert", "alert('" + "YOUR PASSWORD IS INCORRECT" + "');", true);
        }
    }
</script>

<html lang="en">
<head>
    <% Response.Write(BioPM.ClassScripts.BasicScripts.GetMetaScript()); %>

    <title>Competency Development Event Suggestion</title>

    <% Response.Write(BioPM.ClassScripts.StyleScripts.GetCoreStyle()); %>
<% Response.Write(BioPM.ClassScripts.StyleScripts.GetFormStyle()); %>
<% Response.Write(BioPM.ClassScripts.StyleScripts.GetCustomStyle()); %>
</head>

<body>

<section id="container" >
 
<!--header start--> 
 <%Response.Write( BioPM.ClassScripts.SideBarMenu.TopMenuElement(Session["name"].ToString()) ); %> 
<!--header end-->
   
<!--left side bar start-->
 <%Response.Write(BioPM.ClassScripts.SideBarMenu.LeftSidebarMenuElementAutoGenerated(Session["username"].ToString())); %> 
<!--left side bar end-->

    <!--main content start-->
    <section id="main-content">
        <section class="wrapper">
        <!-- page start-->

        <div class="row">
            <div class="col-sm-12">
                <section class="panel">
                    <header class="panel-heading">
                        Competency Development Event Suggestion
                          <span class="tools pull-right">
                            <a class="fa fa-chevron-down" href="javascript:;"></a>
                            <a class="fa fa-times" href="javascript:;"></a>
                         </span>
                    </header>
                    <div class="panel-body">
                        <form id="Form1" class="form-horizontal " runat="server" >

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> EVENT NAME </label>
                            <div class="col-lg-3 col-md-4">
                                <asp:DropDownList ID="ddlEventName" runat="server" class="form-control m-bot15">   
                                </asp:DropDownList> 
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> EMPLOYEE NAME </label>
                            <div class="col-lg-3 col-md-4">
                                <asp:DropDownList ID="ddlEmployeeName" runat="server" class="form-control m-bot15">   
                                </asp:DropDownList> 
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> EVENT MONTH </label>
                            <div class="col-lg-3 col-md-4">
                                <asp:TextBox ID="txtMonth" value="" size="16" class="form-control form-control-inline input-medium default-date-picker" runat="server"></asp:TextBox>
                                <span class="help-block">Begin Date Format : month-day-year e.g. 01-31-2014</span> 
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> COST ETIMATION </label>
                            <div class="col-lg-3 col-md-4">
                                <asp:TextBox ID="txtCost" runat="server" class="form-control m-bot15">   
                                </asp:TextBox> 
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> DURATION </label>
                            <div class="col-lg-3 col-md-4">
                                <asp:TextBox ID="txtDuration" runat="server" class="form-control m-bot15">   
                                </asp:TextBox> 
                            </div>
                        </div>

                        <!-- Modal -->
                        <div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="myModal" class="modal fade">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                        <h4 class="modal-title">Approver Confirmation</h4>
                                    </div>
                                    <div class="modal-body">
                                        <p>You Are Logged In As <% Response.Write(Session["name"].ToString()); %></p><br />
                                        <p>Are you sure to insert into database?</p>
                                        <asp:TextBox ID="txtConfirmation" runat="server" TextMode="Password" placeholder="Confirmation Password" class="form-control placeholder-no-fix"></asp:TextBox>
                                        <asp:TextBox ID="txtReason" TextMode="multiline" Columns="30" Rows="3" runat="server" placeholder="Reason" class="form-control placeholder-no-fix"></asp:TextBox>
                                    </div>
                                    <div class="modal-footer">
                                        <asp:Button ID="btnClose" runat="server" data-dismiss="modal" class="btn btn-default" Text="Cancel"></asp:Button>
                                        <asp:Button ID="btnSubmit" runat="server" class="btn btn-success" Text="Confirm" OnClick="btnSave_Click"></asp:Button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- modal -->

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> </label>
                            <div class="col-lg-3 col-md-3">
                                <asp:LinkButton data-toggle="modal" class="btn btn-round btn-primary" ID="btnAction" runat="server" Text="Add" href="#myModal"/>
                                <asp:Button class="btn btn-round btn-primary" ID="btnCancel" runat="server" Text="Cancel" OnClick="btnCancel_Click"/>
                            </div>
                        </div>
                            
                        </form>
                    </div>
                    
                </section>
            </div>
        </div>
        <!-- page end-->
        </section>
    </section>
    <!--main content end-->
<!--right sidebar start-->
    <%Response.Write(BioPM.ClassScripts.SideBarMenu.RightSidebarMenuElement()); %> 
<!--right sidebar end-->
</section>

<!-- Placed js at the end of the document so the pages load faster -->
    <% Response.Write(BioPM.ClassScripts.JS.GetCoreScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetCustomFormScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetInitialisationScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetPieChartScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetSparklineChartScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetFlotChartScript()); %>
</body>
</html>
