<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="FormInputTrainingExecution.aspx.cs" Inherits="BioPM.FormTrainingExecution" %>

<!DOCTYPE html>
<script runat="server">
    protected void Page_Load(object sender, EventArgs e)
    {
        if (Session["username"] == null && Session["password"] == null) Response.Redirect("PageLogin.aspx");
        if (!IsPostBack)
        {
            GetDataEventAndEmployee();
            ddlRecID.Enabled = false;
            txtExcid.Text = (BioPM.ClassObjects.ComDevExecution.GetComDevExecutionMaxID() + 1).ToString();    
        }
    }    
   
    protected void GetDataEventAndEmployee()
    {
        ddlEventMethod.Items.Clear();
        foreach(object[] data in BioPM.ClassObjects.ComDevEvent.GetAllComdevEvent())
        {
            ddlEventMethod.Items.Add(new ListItem(data[1].ToString(), data[0].ToString()));
        }
        ddlEventMethod.Items.Insert(0, new ListItem("Select Event", "NA"));
        
        ddlEmployeeName.Items.Clear();
        
        foreach (object[] data in BioPM.ClassObjects.EmployeeCatalog.GetAllEmployee())
        {
            ddlEmployeeName.Items.Add(new ListItem(data[1].ToString(), data[0].ToString()));
        }
        ddlEmployeeName.Items.Insert(0, new ListItem("Select Employee", "NA"));
    }
    
    protected void InsertDataIntoDatabase()
    {
        BioPM.ClassObjects.ComDevExecution.InsertComDevExecution(txtExcid.Text, ddlEmployeeName.SelectedValue, ddlEventMethod.SelectedValue, txtEventTitle.Text, txtBatch.Text, txtPembicara.Text, txtCost.Text, txtInsti.Text, txtAdrin.Text, TxtCitin.Text, txtCouin.Text, ddlStatus.SelectedValue.ToString(), txtScore.Text, Session["username"].ToString(), txtBegda.Text, txtEndda.Text, ddlRecID.SelectedValue);
    }

    protected void btnAdd_Click(object sender, EventArgs e)
    {
        InsertDataIntoDatabase();
        Response.Redirect("PageTrainingExecution.aspx");
    }

    protected void btnCancel_Click(object sender, EventArgs e)
    {
        Response.Redirect("PageUserPanel.aspx");
    }

</script>

<html lang="en">
<head>
    <% Response.Write(BioPM.ClassScripts.BasicScripts.GetMetaScript()); %>

    <title>Training Execution</title>

    <% Response.Write(BioPM.ClassScripts.StyleScripts.GetCoreStyle()); %>
<% Response.Write(BioPM.ClassScripts.StyleScripts.GetFormStyle()); %>
<% Response.Write(BioPM.ClassScripts.StyleScripts.GetCustomStyle()); %>
</head>

<body>

<section id="container" >
 
<!--header start--> 
 <%Response.Write( BioPM.ClassScripts.SideBarMenu.TopMenuElement(Session["name"].ToString()) ); %> 
<!--header end-->
   
<!--left side bar start-->
 <%Response.Write(BioPM.ClassScripts.SideBarMenu.LeftSidebarMenuElementAutoGenerated(Session["username"].ToString())); %> 
<!--left side bar end-->

    <!--main content start-->
    <section id="main-content">
        <section class="wrapper">
        <!-- page start-->

        <div class="row">
            <div class="col-sm-12">
                <section class="panel">
                    <header class="panel-heading">
                        Training Execution
                          <span class="tools pull-right">
                            <a class="fa fa-chevron-down" href="javascript:;"></a>
                            <a class="fa fa-times" href="javascript:;"></a>
                         </span>
                    </header>
                    <div class="panel-body">
                        <form id="Form1" class="form-horizontal " runat="server" >                        
                        <div class="form-group">
                            <label class="col-sm-3 control-label"> EXECUTION ID </label>
                            <div class="col-lg-3 col-md-4">
                                <asp:TextBox ID="txtExcid" runat="server" class="form-control m-bot15" placeholder="EXECUTION ID" ReadOnly="true"></asp:TextBox>
                            </div>
                            <asp:RequiredFieldValidator ID="RequiredFieldValidator1" ControlToValidate="txtExcid" runat="server" ErrorMessage="This field is required." ForeColor="Red"></asp:RequiredFieldValidator>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> EMPLOYEE NAME </label>
                            <div class="col-lg-3 col-md-4">
                                <asp:DropDownList ID="ddlEmployeeName" runat="server" class="form-control m-bot15" OnSelectedIndexChanged="ddlEmployeeName_SelectedIndexChanged" AutoPostBack="true">   
                                </asp:DropDownList> 
                            </div>
                        </div>
                        <asp:ScriptManager runat="server" ID="ScriptManager1"></asp:ScriptManager>
                            <asp:UpdatePanel runat="server" ID="UpdatePanel1" UpdateMode="Conditional">
                                <ContentTemplate>
                                    <fieldset>
                        <div class="form-group">
                            <label class="col-sm-3 control-label"> APPROVAL CODE </label>
                            <div class="col-lg-3 col-md-4">
                                <asp:DropDownList ID="ddlRecID" runat="server" class="form-control m-bot15">   
                                </asp:DropDownList> 
                            </div>
                        </div>
                     </fieldset>
                    </ContentTemplate>
                        </asp:UpdatePanel>    
                        <div class="form-group">
                            <label class="col-sm-3 control-label"> EVENT NAME </label>
                            <div class="col-lg-3 col-md-4">
                                <asp:DropDownList ID="ddlEventMethod" runat="server" class="form-control m-bot15">   
                                </asp:DropDownList> 
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> EVENT TITLE </label>
                            <div class="col-lg-3 col-md-4">
                                <asp:TextBox ID="txtEventTitle" runat="server" class="form-control m-bot15" placeholder="EVENT TITLE" ></asp:TextBox>
                            </div>
                            <asp:RequiredFieldValidator ID="RequiredFieldValidator2" ControlToValidate="txtEventTitle" runat="server" ErrorMessage="This field is required." ForeColor="Red"></asp:RequiredFieldValidator>
                        </div>
                        
                        <div class="form-group">
                            <label class="col-sm-3 control-label"> BATCH </label>
                            <div class="col-lg-3 col-md-4">
                                <asp:TextBox ID="txtBatch" runat="server" class="form-control m-bot15" placeholder="BATCH" ></asp:TextBox>
                            </div>
                            <asp:RequiredFieldValidator ID="RequiredFieldValidator3" ControlToValidate="txtBatch" runat="server" ErrorMessage="This field is required." ForeColor="Red"></asp:RequiredFieldValidator>
                        </div>


                        <div class="form-group">
                            <label class="col-sm-3 control-label"> BEGIN DATE </label>
                            <div class="col-md-4 col-lg-3">
                                <asp:TextBox ID="txtBegda" value="" size="16" class="form-control form-control-inline input-medium default-date-picker" runat="server"></asp:TextBox>
                                <span class="help-block">Begin Date Format : month-day-year e.g. 01-31-2014</span>
                            </div>
                            <asp:RequiredFieldValidator ID="RequiredFieldValidator4" ControlToValidate="txtBegda" runat="server" ErrorMessage="This field is required." ForeColor="Red"></asp:RequiredFieldValidator>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> END DATE </label>
                            <div class="col-md-4 col-lg-3">
                                <asp:TextBox ID="txtEndda" value="" size="16" class="form-control form-control-inline input-medium default-date-picker" runat="server"></asp:TextBox>
                                <span class="help-block">End Date Format : month-day-year e.g. 01-31-2014</span>
                            </div>
                            <asp:RequiredFieldValidator ID="RequiredFieldValidator5" ControlToValidate="txtEndda" runat="server" ErrorMessage="This field is required." ForeColor="Red"></asp:RequiredFieldValidator>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> SPEAKER </label>
                            <div class="col-lg-3 col-md-4">
                                <asp:TextBox ID="txtPembicara" runat="server" class="form-control m-bot15" placeholder="SPEAKER" ></asp:TextBox>
                            </div>
                            <asp:RequiredFieldValidator ID="RequiredFieldValidator6" ControlToValidate="txtPembicara" runat="server" ErrorMessage="This field is required." ForeColor="Red"></asp:RequiredFieldValidator>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> COST </label>
                            <div class="col-lg-3 col-md-4">
                                <asp:TextBox ID="txtCost" runat="server" class="form-control m-bot15" placeholder="COST" ></asp:TextBox>
                            </div>
                            <asp:RequiredFieldValidator ID="RequiredFieldValidator7" ControlToValidate="txtCost" runat="server" ErrorMessage="This field is required." ForeColor="Red"></asp:RequiredFieldValidator>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> INSTITUTION </label>
                            <div class="col-lg-3 col-md-4">
                                <asp:TextBox ID="txtInsti" runat="server" class="form-control m-bot15" placeholder="INSTITUTION" ></asp:TextBox>
                            </div>
                            <asp:RequiredFieldValidator ID="RequiredFieldValidator8" ControlToValidate="txtInsti" runat="server" ErrorMessage="This field is required." ForeColor="Red"></asp:RequiredFieldValidator>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> INSTITUTION ADDRESS </label>
                            <div class="col-lg-3 col-md-4">
                                <asp:TextBox ID="txtAdrin" runat="server" class="form-control m-bot15" placeholder="INSTITUTION ADDRESS" ></asp:TextBox>
                            </div>
                            <asp:RequiredFieldValidator ID="RequiredFieldValidator9" ControlToValidate="txtAdrin" runat="server" ErrorMessage="This field is required." ForeColor="Red"></asp:RequiredFieldValidator>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> INSTITUTION CITY </label>
                            <div class="col-lg-3 col-md-4">
                                <asp:TextBox ID="TxtCitin" runat="server" class="form-control m-bot15" placeholder="INSTITUTION CITY" ></asp:TextBox>
                            </div>
                            <asp:RequiredFieldValidator ID="RequiredFieldValidator10" ControlToValidate="txtCitin" runat="server" ErrorMessage="This field is required." ForeColor="Red"></asp:RequiredFieldValidator>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> INSTITUTION COUNTRY </label>
                            <div class="col-lg-3 col-md-4">
                                <asp:TextBox ID="txtCouin" runat="server" class="form-control m-bot15" placeholder="INSTITUTION COUNTRY" ></asp:TextBox>
                            </div>
                            <asp:RequiredFieldValidator ID="RequiredFieldValidator11" ControlToValidate="txtCouin" runat="server" ErrorMessage="This field is required." ForeColor="Red"></asp:RequiredFieldValidator>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> STATUS </label>
                            <div class="col-lg-3 col-md-4">
                                <asp:DropDownList ID="ddlStatus" runat="server" class="form-control m-bot15">  
                                    <asp:ListItem Value="Lulus">Lulus</asp:ListItem> 
                                    <asp:ListItem Value="Tidak Lulus">Tidak Lulus</asp:ListItem> 
                                </asp:DropDownList> 
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> SCORE </label>
                            <div class="col-lg-3 col-md-4">
                                <asp:TextBox ID="txtScore" runat="server" class="form-control m-bot15" placeholder="SCORE" ></asp:TextBox>
                            </div>
                            <asp:RequiredFieldValidator ID="RequiredFieldValidator12" ControlToValidate="txtScore" runat="server" ErrorMessage="This field is required." ForeColor="Red"></asp:RequiredFieldValidator>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> </label>
                            <div class="col-lg-3 col-md-3">
                                <asp:Button class="btn btn-round btn-primary" ID="btnAdd" runat="server" Text="Add" OnClick="btnAdd_Click"/>
                                <asp:Button class="btn btn-round btn-primary" ID="btnCancel" runat="server" Text="Cancel" OnClick="btnCancel_Click"/>
                            </div>
                        </div>  
                        </form>
                    </div>
                    
                </section>
            </div>
        </div>
        <!-- page end-->
        </section>
    </section>
    <!--main content end-->
<!--right sidebar start-->
    <%Response.Write(BioPM.ClassScripts.SideBarMenu.RightSidebarMenuElement()); %> 
<!--right sidebar end-->
</section>

<!-- Placed js at the end of the document so the pages load faster -->
    <% Response.Write(BioPM.ClassScripts.JS.GetCoreScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetCustomFormScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetInitialisationScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetPieChartScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetSparklineChartScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetFlotChartScript()); %>
</body>
</html>
