<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="FormUpdateTargetTraining.aspx.cs" Inherits="BioPM.FormUpdateTargetTraining" %>

<!DOCTYPE html>
<script runat="server">
    string PRQID = null;
    protected void Page_Load(object sender, EventArgs e)
    {
        if (Session["username"] == null && Session["password"] == null) Response.Redirect("PageLogin.aspx");
        if (!IsPostBack)
        {
            SetPositionAndCompetencyList();
            SetDataToForm();
        }
    }

    protected void SetDataToForm()
    {
        object[] values = BioPM.ClassObjects.ComDevEvent.GetComdevEventTargetById(Request.QueryString["key"].ToString());
        txtTrgID.Text = values[0].ToString();
        txtEvtName.Text = values[1].ToString();
        ddlCompetency.SelectedValue = values[3].ToString();
        txtLevelTarget.Text = values[5].ToString();
    }

    protected void SetPositionAndCompetencyList()
    {
        ddlCompetency.Items.Clear();
        foreach (object[] data in BioPM.ClassObjects.CompetencyCatalog.GetAllCompetency())
        {
            ddlCompetency.Items.Add(new ListItem(data[2].ToString(), data[0].ToString()));
        }
    }

    protected void UpdatePositionReqToDatabase()
    {
        BioPM.ClassObjects.ComDevEvent.UpdateComDevEventTarget(txtTrgID.Text, txtEvtName.Text, ddlCompetency.SelectedValue, txtLevelTarget.Text, Session["username"].ToString());
    }

    protected void btnAdd_Click(object sender, EventArgs e)
    {
        if (IsPostBack) UpdatePositionReqToDatabase();
        Response.Redirect("PageCompetencyDevelopmentEvent.aspx");
    }

    protected void btnCancel_Click(object sender, EventArgs e)
    {
        Response.Redirect("PageUserPanel.aspx");
    }

</script>

<html lang="en">
<head>
    <% Response.Write(BioPM.ClassScripts.BasicScripts.GetMetaScript()); %>

    <title>COMDEV EVENT TARGET UPDATE</title>

    <% Response.Write(BioPM.ClassScripts.StyleScripts.GetCoreStyle()); %>
    <% Response.Write(BioPM.ClassScripts.StyleScripts.GetFormStyle()); %>
    <% Response.Write(BioPM.ClassScripts.StyleScripts.GetCustomStyle()); %>
</head>

<body>

<section id="container" >
 
<!--header start--> 
 <%Response.Write( BioPM.ClassScripts.SideBarMenu.TopMenuElement(Session["name"].ToString()) ); %> 
<!--header end-->
   
<!--left side bar start-->
 <%Response.Write(BioPM.ClassScripts.SideBarMenu.LeftSidebarMenuElementAutoGenerated(Session["username"].ToString())); %> 
<!--left side bar end-->

    <!--main content start-->
    <section id="main-content">
        <section class="wrapper">
        <!-- page start-->

        <div class="row">
            <div class="col-sm-12">
                <section class="panel">
                    <header class="panel-heading">
                        COMDEV EVENT TARGET UPDATE
                          <span class="tools pull-right">
                            <a class="fa fa-chevron-down" href="javascript:;"></a>
                            <a class="fa fa-times" href="javascript:;"></a>
                         </span>
                    </header>
                    <div class="panel-body">
                        <form id="Form2" class="form-horizontal " runat="server" >

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> ID TARGET </label>
                            <div class="col-lg-3 col-md-4">
                                <asp:TextBox ID="txtTrgID" runat="server" class="form-control m-bot15" placeholder="PROFICIENCY LEVEL TARGET" ReadOnly="true" ></asp:TextBox>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> EVENT NAME </label>
                            <div class="col-lg-3 col-md-4">
                                <asp:TextBox ID="txtEvtName" runat="server" class="form-control m-bot15" placeholder="PROFICIENCY LEVEL TARGET" ReadOnly="true" ></asp:TextBox>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> COMPETENCY NAME </label>
                            <div class="col-lg-3 col-md-4">
                                <asp:DropDownList ID="ddlCompetency" runat="server" class="form-control m-bot15">   
                                </asp:DropDownList> 
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> PROFICIENCY LEVEL TARGET </label>
                            <div class="col-lg-3 col-md-4">
                                <asp:TextBox ID="txtLevelTarget" runat="server" class="form-control m-bot15" placeholder="PROFICIENCY LEVEL TARGET" ></asp:TextBox>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> </label>
                            <div class="col-lg-3 col-md-3">
                                <asp:Button class="btn btn-round btn-primary" ID="btnAdd" runat="server" Text="Update" OnClick="btnAdd_Click"/>
                                <asp:Button class="btn btn-round btn-primary" ID="btnCancel" runat="server" Text="Cancel" OnClick="btnCancel_Click"/>
                            </div>
                        </div>
                            
                        </form>
                    </div>
                    
                </section>
            </div>
        </div>
        <!-- page end-->
        </section>
    </section>
    <!--main content end-->
<!--right sidebar start-->
    <%Response.Write(BioPM.ClassScripts.SideBarMenu.RightSidebarMenuElement()); %> 
<!--right sidebar end-->
</section>

<!-- Placed js at the end of the document so the pages load faster -->
   
<% Response.Write(BioPM.ClassScripts.JS.GetCoreScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetCustomFormScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetInitialisationScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetPieChartScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetSparklineChartScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetFlotChartScript()); %>
</body>
</html>

