<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="FormApproveLabelPrint.aspx.cs" Inherits="BioPM.FormApproveLabelPrint" %>

<!DOCTYPE html>
<script runat="server">
    private const int _firstEditCellIndexReviewer = 2;
   
    
    protected void Page_Load(object sender, EventArgs e)
    {
        if (Session["username"] == null && Session["password"] == null) Response.Redirect("PageLogin.aspx");
        
        if (!IsPostBack)
        {
            SetDataToForm();
        }
    }
    
    protected void SetDataToForm()
    {
        object[] values = BioPM.ClassObjects.LabelCatalog.GetLabelPrintDataByPrintID(Request.QueryString["key"]);
        txtBatch.Text = values[0].ToString();
        txtGin.Text = values[1].ToString();
        txtProductName.Text = values[2].ToString();
        txtProductionDate.Text = values[3].ToString();
        txtExpiredDate.Text = values[4].ToString();
        txtLabelName.Text = values[5].ToString();
        txtRequestDate.Text = values[6].ToString();
        txtPrintStatus.Text = values[7].ToString() == "" ? "First-Print" : "Re-Print";
        txtQuantity.Text = values[8].ToString();
        txtNumberOfLabel.Text = values[9].ToString();
        txtReason.Text = values[10].ToString();
        
        if (values[7].ToString() == "X")
        {
            lblNumberOfLabel.Visible = true;
            lblReason.Visible = true;
            txtNumberOfLabel.Visible = true;
            txtReason.Visible = true;
        }
        
    }
    
    protected void InsertLabelPrintFlow()
    {
        BioPM.ClassObjects.LabelCatalog.InsertLabelPrintFlow(Request.QueryString["key"], "1", ddlApprovalStatus.SelectedValue, Session["username"].ToString(), txtNote.Text, Session["username"].ToString());  
    }
    
    protected void btnSave_Click(object sender, EventArgs e)
    {
        if (Session["password"].ToString() == BioPM.ClassEngines.CryptographFactory.Encrypt(txtConfirmation.Text, true))
        {
            InsertLabelPrintFlow();
            Response.Redirect("PageLabelPrintApproval.aspx");
        }
        else
        {
            ClientScript.RegisterStartupScript(this.GetType(), "myalert", "alert('" + "YOUR PASSWORD IS INCORRECT" + "');", true);
        }
    }

    protected void btnCancel_Click(object sender, EventArgs e)
    {
        Response.Redirect("PageUserPanel.aspx");
    }
    
</script>

<html lang="en">
<head>
    <% Response.Write(BioPM.ClassScripts.BasicScripts.GetMetaScript()); %>

    <title>Label Print Approver</title>
    
    <% Response.Write(BioPM.ClassScripts.StyleScripts.GetCoreStyle()); %>
    <% Response.Write(BioPM.ClassScripts.StyleScripts.GetGritterStyle()); %>
    <% Response.Write(BioPM.ClassScripts.StyleScripts.GetFormStyle()); %>
    <% Response.Write(BioPM.ClassScripts.StyleScripts.GetCustomStyle()); %>
</head>

<body>

<section id="container" >
 
<!--header start--> 
 <%Response.Write( BioPM.ClassScripts.SideBarMenu.TopMenuElement(Session["name"].ToString()) ); %> 
<!--header end-->
   
<!--left side bar start-->
 <%Response.Write(BioPM.ClassScripts.SideBarMenu.LeftSidebarMenuElementAutoGenerated(Session["username"].ToString())); %> 
<!--left side bar end-->

    <!--main content start-->
    <section id="main-content">
        <section class="wrapper">
        <!-- page start-->

        <div class="row">
            <div class="col-sm-12">
                <section class="panel">
                    <header class="panel-heading">
                        Label Print Approver
                          <span class="tools pull-right">
                            <a class="fa fa-chevron-down" href="javascript:;"></a>
                            <a class="fa fa-times" href="javascript:;"></a>
                         </span>
                    </header>
                    <div class="panel-body">
                        <form class="form-horizontal " runat="server" >
                       
                        <div class="form-group">
                            <asp:Label runat="server" class="col-sm-3 control-label"> REQUEST DATE </asp:Label>
                            <div class="col-lg-3 col-md-4">
                                <asp:Label ID="txtRequestDate" runat="server" class="form-control m-bot15"></asp:Label>
                            </div>
                        </div>

                        <div class="form-group">
                            <asp:Label runat="server" class="col-sm-3 control-label"> BATCH </asp:Label>
                            <div class="col-lg-3 col-md-4">
                                <asp:Label ID="txtBatch" runat="server" class="form-control m-bot15"></asp:Label>
                            </div>
                        </div>

                        <div class="form-group">
                            <asp:Label runat="server" class="col-sm-3 control-label"> GIN </asp:Label>
                            <div class="col-lg-3 col-md-4">
                                  <asp:Label ID="txtGin" runat="server" class="form-control m-bot15"></asp:Label>
                            </div>
                        </div>

                        <div class="form-group">
                            <asp:Label runat="server" ID="lblProductName" class="col-sm-3 control-label"> PRODUCT NAME </asp:Label>
                            <div class="col-lg-3 col-md-4">
                                <asp:Label ID="txtProductName" runat="server" class="form-control m-bot15"></asp:Label>
                            </div>
                        </div>

                        <div class="form-group">
                            <asp:Label runat="server" ID="lblProductionDate" class="col-sm-3 control-label"> PRODUCTION DATE </asp:Label>
                            <div class="col-lg-3 col-md-4">
                                <asp:Label ID="txtProductionDate" runat="server" class="form-control m-bot15"></asp:Label>
                            </div>
                        </div>

                        <div class="form-group">
                            <asp:Label runat="server" ID="lblExpiredDate" class="col-sm-3 control-label"> EXPIRED DATE </asp:Label>
                            <div class="col-lg-3 col-md-4">
                                <asp:Label ID="txtExpiredDate" runat="server" class="form-control m-bot15"></asp:Label>
                            </div>
                        </div>

                        <div class="form-group">
                            <asp:Label runat="server" ID="lblLabelName" class="col-sm-3 control-label"> LABEL NAME </asp:Label>
                            <div class="col-lg-3 col-md-4">
                                <asp:Label ID="txtLabelName" runat="server" class="form-control m-bot15"></asp:Label>
                            </div>
                        </div>

                        <div class="form-group">
                            <asp:Label runat="server" ID="lblQuantity" class="col-sm-3 control-label"> QUANTITY NUMBER </asp:Label>
                            <div class="col-lg-3 col-md-4">
                                <asp:Label ID="txtQuantity" runat="server" class="form-control m-bot15"></asp:Label>
                            </div>
                        </div>

                        <div class="form-group">
                            <asp:Label runat="server" ID="lblPrintStatus" class="col-sm-3 control-label"> PRINT STATUS </asp:Label>
                            <div class="col-lg-3 col-md-4">
                                <asp:Label ID="txtPrintStatus" runat="server" class="form-control m-bot15"></asp:Label>
                            </div>
                        </div>

                        <div class="form-group">
                            <asp:Label runat="server" ID="lblNumberOfLabel" Visible="false" class="col-sm-3 control-label"> NUMBER OF LABEL </asp:Label>
                            <div class="col-lg-3 col-md-4">
                                <asp:Label ID="txtNumberOfLabel" Visible="false" runat="server" class="form-control m-bot15"></asp:Label>
                            </div>
                        </div>

                        <div class="form-group">
                            <asp:Label runat="server" ID="lblReason" Visible="false" class="col-sm-3 control-label"> REASON </asp:Label>
                            <div class="col-lg-3 col-md-4">
                                <asp:Label ID="txtReason" TextMode="MultiLine" Visible="false" runat="server" class="form-control m-bot15"></asp:Label>
                            </div>
                        </div>
                        
                        <!-- Modal -->
                        <div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="myModal" class="modal fade">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                        <h4 class="modal-title">Approver Confirmation</h4>
                                    </div>
                                    <div class="modal-body">
                                        <p>You Are Logged In As <% Response.Write(Session["name"].ToString()); %></p>
                                        <asp:DropDownList ID="ddlApprovalStatus" runat="server" class="form-control m-bot15">
                                            <asp:ListItem Value="APPROVE">Approve</asp:ListItem> 
                                            <asp:ListItem Value="CORECTION">Corection</asp:ListItem>
                                            <asp:ListItem Value="UNAPPROVE">Unapprove</asp:ListItem>
                                        </asp:DropDownList>
                                        <asp:TextBox ID="txtNote" runat="server" TextMode="MultiLine" placeholder="Your Note If Any" class="form-control placeholder-no-fix"></asp:TextBox>
                                        <p></p>
                                        <asp:TextBox ID="txtConfirmation" runat="server" TextMode="Password" placeholder="Confirmation Password" class="form-control placeholder-no-fix"></asp:TextBox>

                                    </div>
                                    <div class="modal-footer">
                                        <asp:Button ID="btnClose" runat="server" data-dismiss="modal" class="btn btn-default" Text="Cancel"></asp:Button>
                                        <asp:Button ID="btnSubmit" runat="server" class="btn btn-success" Text="Confirm" OnClick="btnSave_Click"></asp:Button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- modal -->
                    
                        <div class="form-group">
                            <label class="col-sm-3 control-label"> </label>
                            <div class="col-lg-3 col-md-3">
                                <asp:LinkButton data-toggle="modal" class="btn btn-round btn-primary" ID="btnAction" runat="server" Text="Approve" href="#myModal"/>
                                <asp:Button class="btn btn-round btn-primary" ID="btnCancel" Visible="true" runat="server" Text="Cancel" OnClick="btnCancel_Click"/>
                            </div>
                        </div>

                        </form>
                    </div>

                    
                </section>
            </div>
        </div>
        <!-- page end-->
        </section>
    </section>
    <!--main content end-->
<!--right sidebar start-->
    <%Response.Write(BioPM.ClassScripts.SideBarMenu.RightSidebarMenuElement()); %> 
<!--right sidebar end-->
</section>

<!-- Placed js at the end of the document so the pages load faster -->
<% Response.Write(BioPM.ClassScripts.JS.GetCoreScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetCustomFormScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetInitialisationScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetPieChartScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetSparklineChartScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetFlotChartScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetGritterScript()); %>
</body>
</html>
