<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="PageSurveyAnswers.aspx.cs" Inherits="BioPM.PageSurveyAnswers" %>

<!DOCTYPE html>
<script runat="server">
    string EVTID = null;
    protected void Page_Load(object sender, EventArgs e)
    {
        if (Session["username"] == null && Session["password"] == null) Response.Redirect("PageLogin.aspx");
        if (!IsPostBack)
        {
            SetEmployee();
        }
    }

    protected void SetEmployee()
    {
        ddlEmployeeName.Items.Clear();
        foreach (object[] data in BioPM.ClassObjects.EmployeeCatalog.GetAllEmployee())
        {
            ddlEmployeeName.Items.Add(new ListItem(data[1].ToString(), data[0].ToString()));
        }
        ddlEmployeeName.Items.Insert(0, new ListItem("Select Employee", "NA"));
    }

    protected void btnCancel_Click(object sender, EventArgs e)
    {
        Response.Redirect("PageUserPanel.aspx");
    }

    protected void btnAdd_Click(object sender, EventArgs e)
    {
        if(ddlKodeSurvey.SelectedValue=="1")
            Response.Redirect("PageEvaluasiReaksiPeserta.aspx?key=" + ddlExecution.SelectedValue + "");
        else if (ddlKodeSurvey.SelectedValue == "3")
            Response.Redirect("PageEvaluasiPerilaku.aspx?key=" + ddlExecution.SelectedValue + "");
    }
   
</script>

<html lang="en">
<head>
    <% Response.Write(BioPM.ClassScripts.BasicScripts.GetMetaScript()); %>

    <title>Evaluation Answers</title>

    <% Response.Write(BioPM.ClassScripts.StyleScripts.GetCoreStyle()); %>
    <% Response.Write(BioPM.ClassScripts.StyleScripts.GetFormStyle()); %>
    <% Response.Write(BioPM.ClassScripts.StyleScripts.GetCustomStyle()); %>
</head>

<body>

<section id="container" >
 
<!--header start--> 
 <%Response.Write( BioPM.ClassScripts.SideBarMenu.TopMenuElement(Session["name"].ToString()) ); %> 
<!--header end-->
   
<!--left side bar start-->
 <%Response.Write(BioPM.ClassScripts.SideBarMenu.LeftSidebarMenuElementAutoGenerated(Session["username"].ToString())); %> 
<!--left side bar end-->

    <!--main content start-->
    <section id="main-content">
        <section class="wrapper">
        <!-- page start-->

        <div class="row">
            <div class="col-sm-12">
                <section class="panel">
                    <header class="panel-heading">
                        Evaluation Answers
                          <span class="tools pull-right">
                            <a class="fa fa-chevron-down" href="javascript:;"></a>
                            <a class="fa fa-times" href="javascript:;"></a>
                         </span>
                    </header>
                    <div class="panel-body">
                        <form id="Form1" class="form-horizontal " runat="server" >
                            <asp:ScriptManager runat="server" ID="ScriptManager1"></asp:ScriptManager>
                            <asp:UpdatePanel runat="server" ID="UpdatePanel1" UpdateMode="Conditional">
                                <ContentTemplate>
                                    <fieldset>
                                        <legend>Evaluation Responses</legend>
                                        <div class="form-group">
                                            <label class="col-sm-3 control-label" > EMPLOYEE NAME </label>
                                            <div class="col-lg-3 col-md-4">
                                                <asp:DropDownList ID="ddlEmployeeName" runat="server" class="form-control m-bot15" OnSelectedIndexChanged="ddlEmployeeName_SelectedIndexChanged" AutoPostBack="true">   
                                                </asp:DropDownList>
                                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> COMDEV EXECUTION </label>
                            <div class="col-lg-3 col-md-4">
                                <asp:DropDownList ID="ddlExecution" runat="server" class="form-control m-bot15" OnSelectedIndexChanged="ddlExecution_SelectedIndexChanged" AutoPostBack="true" Enabled="False">   
                                </asp:DropDownList> 
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> EVALUATION </label>
                            <div class="col-lg-3 col-md-4">
                                <asp:DropDownList ID="ddlKodeSurvey" runat="server" class="form-control m-bot15" Enabled="False">
                                    <asp:ListItem value="1">Evaluation 1</asp:ListItem>   
                                    <asp:ListItem value="2">Evaluation 2</asp:ListItem>   
                                    <asp:ListItem value="3">Evaluation 3</asp:ListItem>   
                                </asp:DropDownList> 
                            </div>
                        </div>
                        </fieldset>
                    </ContentTemplate>
                </asp:UpdatePanel>                       

                       <div class="form-group">
                            <label class="col-sm-3 control-label"> </label>
                            <div class="col-lg-3 col-md-3">
                                <asp:Button class="btn btn-round btn-primary" ID="btnAdd" runat="server" Text="View" OnClick="btnAdd_Click"/>
                                <asp:Button class="btn btn-round btn-primary" ID="btnCancel" runat="server" Text="Cancel" OnClick="btnCancel_Click"/>
                            </div>
                        </div>
                            
                        </form>
                    </div>
                    
                </section>
            </div>
        </div>
        <!-- page end-->
        </section>
    </section>
    <!--main content end-->
<!--right sidebar start-->
    <%Response.Write(BioPM.ClassScripts.SideBarMenu.RightSidebarMenuElement()); %> 
<!--right sidebar end-->
</section>

<!-- Placed js at the end of the document so the pages load faster -->
   
<% Response.Write(BioPM.ClassScripts.JS.GetCoreScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetCustomFormScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetInitialisationScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetPieChartScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetSparklineChartScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetFlotChartScript()); %>
</body>
</html>
