<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="PageTrainingSurvey.aspx.cs" Inherits="BioPM.PageTrainingSurvey" %>

<!DOCTYPE html>
<script runat="server">
    protected void Page_Load(object sender, EventArgs e)
    {
        if (Session["username"] == null && Session["password"] == null) Response.Redirect("PageLogin.aspx");
    }

    protected String GenerateDataEksekusi()
    {
        string htmlelement = "";
        string status1, status2, status3 = null;
        string html1=null, html2=null, html3 = null;
        foreach (object[] data in BioPM.ClassObjects.ComDevExecution.GetComdevExecutionByUserId(Session["username"].ToString()))
        {

            status1 = BioPM.ClassObjects.Survey.GetJumlahJawaban(data[0].ToString(), "1");
            status2 = BioPM.ClassObjects.Survey.GetJumlahJawaban(data[0].ToString(), "2");
            status3 = BioPM.ClassObjects.Survey.GetJumlahJawaban(data[0].ToString(), "3");
            if (status1 == "Selesai")
                html1 = "Sudah Selesai";
            else if (status1 == "Belum Diisi")
                html1 = "<a class='edit' href='FormEvaluasiReaksiPeserta.aspx?key=" + data[0].ToString() + "'>Survey 1</a>";

            if (status2 == "Selesai")
                html2 = "Sudah Selesai";
            else if (status2 == "Belum Diisi")
                html2 = "<a class='edit' href='#.aspx?key=" + data[0].ToString() + "'>Survey 2</a>";

            if (status3 == "Selesai")
                html3 = "Sudah Selesai";
            else if (status3 == "Belum Diisi")
                html3 = "Belum Diisi";

            object[] values = BioPM.ClassObjects.EmployeeCatalog.GetEmployeeByID(Session["username"].ToString());
            htmlelement += "<tr class=''><td>" + data[1].ToString() + "</td><td>" + values[1].ToString() + "</td><td>" + values[2].ToString() + "</td><td>" + values[3].ToString() + "</td><td>" + data[2].ToString() + "</td><td>" + data[3].ToString() + "</td><td>" + html1 + "</td><td>" + html2 + "</td><td>" + html3 + "</td></tr>";
        }
        
        return htmlelement;
    }
</script>

<html lang="en">
<head>
    <% Response.Write(BioPM.ClassScripts.BasicScripts.GetMetaScript()); %>

    <title>Comdev Event Evaluation</title>

    <% Response.Write(BioPM.ClassScripts.StyleScripts.GetCoreStyle()); %>
<% Response.Write(BioPM.ClassScripts.StyleScripts.GetTableStyle()); %>
<% Response.Write(BioPM.ClassScripts.StyleScripts.GetCustomStyle()); %>
</head>

<body>

<section id="container" >
 
<!--header start--> 
 <%Response.Write( BioPM.ClassScripts.SideBarMenu.TopMenuElement(Session["name"].ToString())); %> 
<!--header end-->
   
<!--left side bar start-->
 <%Response.Write(BioPM.ClassScripts.SideBarMenu.LeftSidebarMenuElementAutoGenerated(Session["username"].ToString())); %> 
<!--left side bar end-->

    <!--main content start-->
    <section id="main-content">
        <section class="wrapper">
        <!-- page start-->

        <div class="row">
            <div class="col-sm-12">
                <section class="panel">
                    <header class="panel-heading">
                        Comdev Event Evaluation
                          <span class="tools pull-right">
                            <a class="fa fa-chevron-down" href="javascript:;"></a>
                            <a class="fa fa-times" href="javascript:;"></a>
                         </span>
                    </header>
                    <div class="panel-body">

                        <div class="adv-table">
                            <div class="clearfix">
                                <div class="btn-group pull-right">
                                    <button class="btn btn-default dropdown-toggle" data-toggle="dropdown">Tools <i class="fa fa-angle-down"></i>
                                    </button>
                                    <ul class="dropdown-menu pull-right">
                                        <li><a href="#">Print</a></li>
                                        <li><a href="#">Save as PDF</a></li>
                                        <li><a href="#">Export to Excel</a></li>
                                    </ul>
                                </div>
                            </div>
                            <table class="table table-striped table-hover table-bordered" id="dynamic-table" >
                                <thead>
                                <tr>
                                    <th>Employee ID</th>
                                    <th>Employee Name</th>
                                    <th>Position</th>
                                    <th>Unit</th>
                                    <th>Event Title</th>
                                    <th>Batch</th>
                                    <th>Evaluasi 1</th>                                       
                                    <th>Evaluasi 2</th>
                                    <th>Evaluasi 3</th>
                                </tr>
                                </thead>
                                <tbody>
                                <% Response.Write(GenerateDataEksekusi()); %>
                                </tbody>
                            </table>
                        </div>
                        

                    </div>
                    
                </section>
            </div>
        </div>

        <!-- page end-->
        </section>
    </section>
    <!--main content end-->
<!--right sidebar start-->
    <%Response.Write( BioPM.ClassScripts.SideBarMenu.RightSidebarMenuElement() ); %> 
<!--right sidebar end-->
</section>

<!-- Placed js at the end of the document so the pages load faster -->
    <% Response.Write(BioPM.ClassScripts.JS.GetCoreScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetDynamicTableScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetInitialisationScript()); %>
</body>
</html>
