<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="PageRekapEvaluasiPelaksanaan.aspx.cs" Inherits="BioPM.PageRekapEvaluasi" %>

<!DOCTYPE html>
<script runat="server">
    protected void Page_Load(object sender, EventArgs e)
    {
        if (Session["username"] == null && Session["password"] == null) Response.Redirect("PageLogin.aspx");
    }

    protected String GenerateDataEvent()
    {
        string htmlelement = "";

        foreach (object[] data in BioPM.ClassObjects.ComDevEvent.GetAllComdevEvent())
        {
            htmlelement += "<tr class=''><td>" + data[1].ToString() + "</td><td>" + data[2].ToString() + "</td><td>" + data[3].ToString() + "</td><td><a class='edit' href='PageTargetTrainingK.aspx?key=" + data[0].ToString() + "'>View</a></td></tr>";
        }
        
        return htmlelement;
    }

    protected void btnShow_Click()
    {

    }

</script>

<html lang="en">
<head>
    <% Response.Write(BioPM.ClassScripts.BasicScripts.GetMetaScript()); %>

    <title>Rekap Evaluasi Pelaksanaan</title>

    <% Response.Write(BioPM.ClassScripts.StyleScripts.GetCoreStyle()); %>
<% Response.Write(BioPM.ClassScripts.StyleScripts.GetTableStyle()); %>
<% Response.Write(BioPM.ClassScripts.StyleScripts.GetCustomStyle()); %>
</head>

<body>

<section id="container" >
 
<!--header start--> 
 <%Response.Write( BioPM.ClassScripts.SideBarMenu.TopMenuElement(Session["name"].ToString())); %> 
<!--header end-->
   
<!--left side bar start-->
 <%Response.Write(BioPM.ClassScripts.SideBarMenu.LeftSidebarMenuElementAutoGenerated(Session["username"].ToString())); %> 
<!--left side bar end-->

    <!--main content start-->
    <section id="main-content">
        <section class="wrapper">
        <!-- page start-->
        <div class="row">
            <div class="col-sm-12">
                <section class="panel">
                    <header class="panel-heading">
                        Rekap Evaluasi Pelaksanaan
                          <span class="tools pull-right">
                            <a class="fa fa-chevron-down" href="javascript:;"></a>
                            <a class="fa fa-times" href="javascript:;"></a>
                         </span>
                    </header>
                    <div class="panel-body">

                        <div class="adv-table">
                            <div class="clearfix">
                                <div class="btn-group pull-right">
                                    <button class="btn btn-default dropdown-toggle" data-toggle="dropdown">Tools <i class="fa fa-angle-down"></i>
                                    </button>
                                    <ul class="dropdown-menu pull-right">
                                        <li><a href="#">Print</a></li>
                                        <li><a href="#">Save as PDF</a></li>
                                        <li><a href="#">Export to Excel</a></li>
                                    </ul>
                                </div>
                            </div>
                            <form id="Form2" class="form-horizontal " runat="server" >
                                <div class="form-group">
                                    <label class="col-sm-3 control-label"> EVENT </label>
                                    <div class="col-lg-3 col-md-4">
                                        <asp:DropDownList ID="ddlEvent" runat="server" class="form-control m-bot15">   
                                        </asp:DropDownList> 
                                    </div>
                                </div> 
                                <div class="form-group">
                                    <label class="col-sm-3 control-label"> BATCH </label>
                                    <div class="col-lg-3 col-md-4">
                                        <asp:DropDownList ID="ddlBatch" runat="server" class="form-control m-bot15">   
                                        </asp:DropDownList> 
                                    </div>
                                </div> 
                                <div class="btn-group">
                                  <button id="editable-sample_new" onclick="document.location.href='PageRekapEvaluasiPelaksanaan.aspx';" class="btn btn-primary"> View
                                  </button>
                                </div>
                            </form>
                            <table class="table table-striped table-hover table-bordered" id="dynamic-table">
                                <thead>
                                    <tr>                                
                                        <th>Aspek</th>
                                        <th>5</th>
                                        <th>4</th>
                                        <th>3</th>
                                        <th>2</th>
                                        <th>1</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td colspan="6">
                                            <h4>I. Tanggapan atas materi pelatihan</h4>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Kejelasan bahasa materi pelatihan</td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td>Sistematika penulisan materi</td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td>Kemudahan dalam memahami materi pelatihan secara keseluruhan</td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td>Kualitas materi pelatihan & kedalaman materi pelatihan</td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td colspan="6">
                                            <h4>II. Tanggapan atas instruktur</h4>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Pengetahuan teoritis atas materi pelatihan</td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td>Pengalaman yang mendukung atas materi pelatihan</td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td>Kemampuan menguasai audiens (peserta pelatihan)</td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td>Kemampuan menjawab pertanyaan dari peserta pelatihan</td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td>Cara penyampaian materi pelatihan</td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td colspan="6">
                                            <h4>III. Tanggapan atas fasilitas pelatihan</h4>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Tempat/lokasi pelatihan/makanan</td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td>Media pelatihan</td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td colspan="6">
                                            <h4>IV. Waktu pelaksanaan pelatihan</h4>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Tanggal/hari pelaksanaan pelatihan</td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td>Total waktu pelaksanaan pelatihan</td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td>Pengalokasian waktu/susunan acara pelatihan</td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                    
                                    <tr>
                                        <td colspan="6">
                                            <h4>V. Tanggapan atas program pelatihan</h4>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Kesesuaian isi program terhadap sasaran pelatihan</td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td>Apakah program pelatihan ini memenuhi harapan?</td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    
                </section>
            </div>
        </div>
        <!-- page end-->
        </section>
    </section>
    <!--main content end-->
<!--right sidebar start-->
    <%Response.Write( BioPM.ClassScripts.SideBarMenu.RightSidebarMenuElement() ); %> 
<!--right sidebar end-->
</section>

<!-- Placed js at the end of the document so the pages load faster -->
    <% Response.Write(BioPM.ClassScripts.JS.GetCoreScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetDynamicTableScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetInitialisationScript()); %>
</body>
</html>
