<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="PageRekapEvaluasiPerilaku.aspx.cs" Inherits="BioPM.PageRekapDataEvaluasi" %>

<%@ Register assembly="AjaxControlToolkit" namespace="AjaxControlToolkit" tagprefix="asp" %>

<!DOCTYPE html>
<script runat="server">
    protected void Page_Load(object sender, EventArgs e)
    {
        Page.Header.DataBind();
        Page.DataBind();
        if (Session["username"] == null && Session["password"] == null) Response.Redirect("PageLogin.aspx");
        if (!IsPostBack)
        {
            GetDataEventandBatch();
        }
        if (Page.IsPostBack)
        {
            btnShow_Click();
            BindChart();
        }        
    }

    protected void GetDataEventandBatch()
    {
        ddlEvent.Items.Clear();
        foreach (object[] data in BioPM.ClassObjects.ComDevEvent.GetAllComdevEvent())
        {
            ddlEvent.Items.Add(new ListItem(data[1].ToString(), data[0].ToString()));
        }

        ddlBatch.Items.Clear();
        foreach (object[] data in BioPM.ClassObjects.ComDevExecution.GetBatch(ddlEvent.SelectedValue))
        {
            ddlBatch.Items.Add(new ListItem(data[0].ToString()+" - "+data[1].ToString(), data[1].ToString()));
        }
    }

    protected String GenerateDataEvent()
    {
        string htmlelement = "";

        foreach (object[] data in BioPM.ClassObjects.ComDevEvent.GetAllComdevEvent())
        {
            htmlelement += "<tr class=''><td>" + data[1].ToString() + "</td><td>" + data[2].ToString() + "</td><td>" + data[3].ToString() + "</td><td><a class='edit' href='PageTargetTrainingK.aspx?key=" + data[0].ToString() + "'>View</a></td></tr>";
        }
        
        return htmlelement;
    }

    protected void btnShow_Click()
    {
        object[] data1 = BioPM.ClassObjects.Survey.GetRekapSurvey(ddlEvent.SelectedValue, ddlBatch.SelectedValue, "1");
        lbl14.Text = data1[4].ToString();
        lbl13.Text = data1[5].ToString();
        lbl12.Text = data1[6].ToString();
        lbl11.Text = data1[7].ToString();

        object[] data2 = BioPM.ClassObjects.Survey.GetRekapSurvey(ddlEvent.SelectedValue, ddlBatch.SelectedValue, "3");
        lbl24.Text = data2[4].ToString();
        lbl23.Text = data2[5].ToString();
        lbl22.Text = data2[6].ToString();
        lbl21.Text = data2[7].ToString();

        object[] data3 = BioPM.ClassObjects.Survey.GetRekapSurvey(ddlEvent.SelectedValue, ddlBatch.SelectedValue, "5");
        lbl34.Text = data3[4].ToString();
        lbl33.Text = data3[5].ToString();
        lbl32.Text = data3[6].ToString();
        lbl31.Text = data3[7].ToString();
    }

</script>

<html lang="en">
<head runat="server">
    <%# BioPM.ClassScripts.BasicScripts.GetMetaScript() %>

    <title>Rekap Evaluasi Pelaksanaan</title>

    <%# BioPM.ClassScripts.StyleScripts.GetCoreStyle() %>
<%# BioPM.ClassScripts.StyleScripts.GetTableStyle() %>
<%# BioPM.ClassScripts.StyleScripts.GetCustomStyle() %>
</head>

<body>

<section id="container" >
 
<!--header start--> 
 <%# BioPM.ClassScripts.SideBarMenu.TopMenuElement(Session["name"].ToString()) %> 
<!--header end-->
   
<!--left side bar start-->
 <%# BioPM.ClassScripts.SideBarMenu.LeftSidebarMenuElementAutoGenerated(Session["username"].ToString()) %> 
<!--left side bar end-->

    <!--main content start-->
    <section id="main-content">
        <section class="wrapper">
        <!-- page start-->
        <div class="row">
            <div class="col-sm-12">
                <section class="panel">
                    <header class="panel-heading">
                        Rekap Evaluasi Pelaksanaan
                          <span class="tools pull-right">
                            <a class="fa fa-chevron-down" href="javascript:;"></a>
                            <a class="fa fa-times" href="javascript:;"></a>
                         </span>
                    </header>
                    <div class="panel-body">
                        <form id="Form2" class="form-horizontal " runat="server" >
                        <div class="adv-table">
                            <div class="clearfix">
                                <div class="btn-group pull-right">
                                    <button class="btn btn-default dropdown-toggle" data-toggle="dropdown">Tools <i class="fa fa-angle-down"></i>
                                    </button>
                                    <ul class="dropdown-menu pull-right">
                                        <li><a href="#">Print</a></li>
                                        <li><a href="#">Save as PDF</a></li>
                                        <li><a href="#">Export to Excel</a></li>
                                    </ul>
                                </div>
                            </div>                            
                                <div class="form-group">
                                    <label class="col-sm-3 control-label"> EVENT </label>
                                    <div class="col-lg-3 col-md-4">
                                        <asp:DropDownList ID="ddlEvent" runat="server" class="form-control m-bot15">   
                                        </asp:DropDownList> 
                                    </div>
                                </div> 
                                <div class="form-group">
                                    <label class="col-sm-3 control-label"> BATCH </label>
                                    <div class="col-lg-3 col-md-4">
                                        <asp:DropDownList ID="ddlBatch" runat="server" class="form-control m-bot15">   
                                        </asp:DropDownList> 
                                    </div>
                                </div> 
                                <div class="btn-group">
                                      <asp:button id="btnView" runat="server" Text="View" />                                   
                                </div>
                            <table class="table table-striped table-hover table-bordered" id="dynamic-table">
                                <thead>
                                    <tr>                                
                                        <th>Aspek</th>
                                        <th>4</th>
                                        <th>3</th>
                                        <th>2</th>
                                        <th>1</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>Apakah objektif / tujuan pelatihan ini sudah tercapai oleh peserta tersebut? </td>
                                        <td><asp:Label ID="lbl14" runat="server"></asp:Label></td>
                                        <td><asp:Label ID="lbl13" runat="server"></asp:Label></td>
                                        <td><asp:Label ID="lbl12" runat="server"></asp:Label></td>
                                        <td><asp:Label ID="lbl11" runat="server"></asp:Label></td>
                                    </tr>
                                    <tr>
                                        <td>Apakah peserta pelatihan ini sudah mengaplikasikan pengetahuan yang didapat pada pekerjaannya? </td>
                                        <td><asp:Label ID="lbl24" runat="server"></asp:Label></td>
                                        <td><asp:Label ID="lbl23" runat="server"></asp:Label></td>
                                        <td><asp:Label ID="lbl22" runat="server"></asp:Label></td>
                                        <td><asp:Label ID="lbl21" runat="server"></asp:Label></td>
                                    </tr>
                                    <tr>
                                        <td>Bagaimana penilaian anda atas hasil yang telah dicapai oleh karyawan tersebut? </td>
                                        <td><asp:Label ID="lbl34" runat="server"></asp:Label></td>
                                        <td><asp:Label ID="lbl33" runat="server"></asp:Label></td>
                                        <td><asp:Label ID="lbl32" runat="server"></asp:Label></td>
                                        <td><asp:Label ID="lbl31" runat="server"></asp:Label></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                            <asp:ScriptManager ID="ScriptManager1" runat="server"></asp:ScriptManager>
                            <asp:BarChart ID="barchart1" runat="server" ChartHeight="300" ChartWidth="600" ChartType="Column" ChartTitle="Evaluation Recap"></asp:BarChart>
                        </form>                            
                        </div>                    
                </section>
            </div>
        </div>
        <!-- page end-->
        </section>
    </section>
    <!--main content end-->
<!--right sidebar start-->
    <%# BioPM.ClassScripts.SideBarMenu.RightSidebarMenuElement() %> 
<!--right sidebar end-->
</section>

<!-- Placed js at the end of the document so the pages load faster -->
    <%# BioPM.ClassScripts.JS.GetCoreScript() %>
<%# BioPM.ClassScripts.JS.GetDynamicTableScript() %>
<%# BioPM.ClassScripts.JS.GetInitialisationScript() %>

</body>
</html>
