<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="PageSampleMWGT.aspx.cs" Inherits="BioPM.PageSampleMWGT" %>

<!DOCTYPE html>
<script runat="server">
    string itmnm, qcname, tesdt, animalpercage;
    protected void Page_Load(object sender, EventArgs e)
    {
        if (Session["username"] == null && Session["password"] == null) Response.Redirect("PageLogin.aspx");
        if (Session["id"] == null) Response.Redirect("PageUserPanel.aspx");
        
        SetDataQCTest();
    }
    protected void sessionCreator()
    {     
        Session["username"] = "K495";
        Session["name"] = "ALLAN PRAKOSA";
        Session["password"] = "admin1234";
        Session["id"] = "1";
        Session["role"] = "111111";
    }
    
    protected void SetDataQCTest()
    {
        object[] values = BioPM.ClassObjects.QualityControlCatalog.GetAllMWGTByID(Session["id"].ToString())[0]; ;
        itmnm = values[3].ToString();
        qcname = values[2].ToString();
        animalpercage = values[5].ToString();
        tesdt = BioPM.ClassEngines.DateFormatFactory.GetDateFormat(values[1].ToString());
    }

    protected String GenerateDataAnimalTest()
    {
        string htmlelement = "";

        foreach (object[] data in BioPM.ClassObjects.QualityControlCatalog.GetAllMWGTByID(Session["id"].ToString()))
        {
            htmlelement += "<tr class=''><td>" + data[4].ToString() + "</td><td>" + data[7].ToString() + "</td><td>" + data[0].ToString() + "</td><td>" + BioPM.ClassObjects.QualityControlCatalog.GetBatchDetailByBatch(data[0].ToString()).ToString() + "</td></tr>";
        }
        
        return htmlelement;
    }

   
</script>

<html lang="en">
<head>
    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="ThemeBucket">
    <link rel="shortcut icon" href="Scripts/UserPanel/images/favicon.html">

    <title>Random Sample Test</title>

    <% Response.Write(BioPM.ClassScripts.StyleScripts.GetCoreStyle()); %>
<% Response.Write(BioPM.ClassScripts.StyleScripts.GetTableStyle()); %>
<% Response.Write(BioPM.ClassScripts.StyleScripts.GetCustomStyle()); %>
</head>

<body>

<section id="container" >
 
<!--header start--> 
 <%Response.Write( BioPM.ClassScripts.SideBarMenu.TopMenuElement(Session["name"].ToString())); %> 
<!--header end-->
   
<!--left side bar start-->
 <%Response.Write(BioPM.ClassScripts.SideBarMenu.LeftSidebarMenuElementAutoGenerated(Session["username"].ToString())); %> 
<!--left side bar end-->

    <!--main content start-->
    <section id="main-content">
        <section class="wrapper">
        <!-- page start-->

        <div class="row">
            <div class="col-sm-12">
                <section class="panel">
                    <header class="panel-heading">
                        Random Sample Test Result
                          <span class="tools pull-right">
                            <a class="fa fa-chevron-down" href="javascript:;"></a>
                            <a class="fa fa-times" href="javascript:;"></a>
                         </span>
                    </header>
                    <div class="panel-body">
                        <h4>
                                Test Name   : <% Response.Write(" " + qcname); %> <br/>
                                Random Date :  <% Response.Write(" " + tesdt); %> <br/>
                                Animal Name : <% Response.Write(" " + itmnm); %> <br/>
                                Animal Per Cage : <% Response.Write(" " + animalpercage); %> <br/>
                                <br/>
                        </h4>
                        <div class="adv-table">
                            <div class="clearfix">
                                <div class="btn-group">
                                    <button id="editable-sample_new" onclick="document.location.href='PageReportMWGT.aspx';" class="btn btn-primary"> Print <i class="fa fa-print"></i>
                                    </button>
                                </div>
                            </div>
                            <table class="table table-striped table-hover table-bordered" id="dynamic-table" >
                                <thead>
                                <tr>
                                    <th>CAGE NUMBER</th>
                                    <th>SAMPLE NUMBER</th>
                                    <th>BATCH</th>
                                    <th>DETAIL</th>
                                </tr>
                                </thead>
                                <tbody>
                                <% Response.Write(GenerateDataAnimalTest()); %>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    
                </section>
            </div>
        </div>

        <!-- page end-->
        </section>
    </section>
    <!--main content end-->
<!--right sidebar start-->
    <%Response.Write( BioPM.ClassScripts.SideBarMenu.RightSidebarMenuElement() ); %> 
<!--right sidebar end-->
</section>

<!-- Placed js at the end of the document so the pages load faster -->
    <% Response.Write(BioPM.ClassScripts.JS.GetCoreScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetDynamicTableScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetInitialisationScript()); %>
</body>
</html>

