//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioPM {
    
    
    public partial class PageCompetencyRelation {
        
        /// <summary>
<<<<<<< HEAD
        /// Form1 control.
=======
>>>>>>> origin/master
        /// Form2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm Form2;
        
        /// <summary>
<<<<<<< HEAD
        /// ddlCompParent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlCompParent;
        
        /// <summary>
        /// ddlCompChild control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlCompChild;
        
        /// <summary>

        /// txtCompLevel control.

        /// TextBox1 control.
        //protected global::System.Web.UI.HtmlControls.HtmlForm Form2;
        
        /// <summary>
        /// txtConfirmation control.

        //protected global::System.Web.UI.HtmlControls.HtmlForm Form2;
        
        /// <summary>
=======
>>>>>>> origin/master
        /// txtConfirmation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
<<<<<<< HEAD


        protected global::System.Web.UI.WebControls.TextBox txtCompLevel;
        
        /// <summary>
        /// btnAdd control.

        protected global::System.Web.UI.WebControls.TextBox TextBox1;
        protected global::System.Web.UI.WebControls.TextBox txtConfirmation;

        //protected global::System.Web.UI.WebControls.TextBox txtConfirmation;

=======
        protected global::System.Web.UI.WebControls.TextBox txtConfirmation;
>>>>>>> origin/master
        
        /// <summary>
        /// btnClose control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
<<<<<<< HEAD
        protected global::System.Web.UI.WebControls.Button Button1;
=======
>>>>>>> origin/master
        protected global::System.Web.UI.WebControls.Button btnClose;
        
        /// <summary>
        /// btnSubmit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnSubmit;
<<<<<<< HEAD
        //protected global::System.Web.UI.WebControls.Button btnSubmit;
=======
>>>>>>> origin/master
        
        /// <summary>
        /// ddlCompParent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlCompParent;
        
        /// <summary>
        /// ddlCompChild control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlCompChild;
        
        /// <summary>
        /// txtCompLevel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
<<<<<<< HEAD

        //protected global::System.Web.UI.WebControls.TextBox txtCompLevel;

=======
        protected global::System.Web.UI.WebControls.TextBox txtCompLevel;
>>>>>>> origin/master
        
        /// <summary>
        /// btnAction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton btnAction;
<<<<<<< HEAD
        //protected global::System.Web.UI.WebControls.LinkButton btnAction;

=======
>>>>>>> origin/master
    }
}
